// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dat_UserData.proto

package cn.wzj.netty.proto;

public final class DatUserData {
  private DatUserData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DAT_UserDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.DAT_UserData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ����UID
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <pre>
     * ����UID
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <pre>
     * ����UID
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     * �����ǳ�
     * </pre>
     *
     * <code>required string nickname = 2;</code>
     */
    boolean hasNickname();
    /**
     * <pre>
     * �����ǳ�
     * </pre>
     *
     * <code>required string nickname = 2;</code>
     */
    java.lang.String getNickname();
    /**
     * <pre>
     * �����ǳ�
     * </pre>
     *
     * <code>required string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <pre>
     * ���ҵȼ�
     * </pre>
     *
     * <code>required int32 lv = 3;</code>
     */
    boolean hasLv();
    /**
     * <pre>
     * ���ҵȼ�
     * </pre>
     *
     * <code>required int32 lv = 3;</code>
     */
    int getLv();

    /**
     * <pre>
     * ����ֵ
     * </pre>
     *
     * <code>required int32 experience = 4;</code>
     */
    boolean hasExperience();
    /**
     * <pre>
     * ����ֵ
     * </pre>
     *
     * <code>required int32 experience = 4;</code>
     */
    int getExperience();

    /**
     * <pre>
     * ���ҽ�ɫid
     * </pre>
     *
     * <code>required string roleId = 5;</code>
     */
    boolean hasRoleId();
    /**
     * <pre>
     * ���ҽ�ɫid
     * </pre>
     *
     * <code>required string roleId = 5;</code>
     */
    java.lang.String getRoleId();
    /**
     * <pre>
     * ���ҽ�ɫid
     * </pre>
     *
     * <code>required string roleId = 5;</code>
     */
    com.google.protobuf.ByteString
        getRoleIdBytes();

    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 strength = 6;</code>
     */
    boolean hasStrength();
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 strength = 6;</code>
     */
    int getStrength();

    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magic = 7;</code>
     */
    boolean hasMagic();
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magic = 7;</code>
     */
    int getMagic();

    /**
     * <pre>
     * ���ݶ�
     * </pre>
     *
     * <code>required int32 agility = 8;</code>
     */
    boolean hasAgility();
    /**
     * <pre>
     * ���ݶ�
     * </pre>
     *
     * <code>required int32 agility = 8;</code>
     */
    int getAgility();

    /**
     * <pre>
     * ����Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
     */
    boolean hasElementProperty();
    /**
     * <pre>
     * ����Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
     */
    cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getElementProperty();
    /**
     * <pre>
     * ����Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
     */
    cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder getElementPropertyOrBuilder();

    /**
     * <pre>
     * ����ӵ�е�����Ӣ��
     * </pre>
     *
     * <code>repeated string heroes = 10;</code>
     */
    java.util.List<java.lang.String>
        getHeroesList();
    /**
     * <pre>
     * ����ӵ�е�����Ӣ��
     * </pre>
     *
     * <code>repeated string heroes = 10;</code>
     */
    int getHeroesCount();
    /**
     * <pre>
     * ����ӵ�е�����Ӣ��
     * </pre>
     *
     * <code>repeated string heroes = 10;</code>
     */
    java.lang.String getHeroes(int index);
    /**
     * <pre>
     * ����ӵ�е�����Ӣ��
     * </pre>
     *
     * <code>repeated string heroes = 10;</code>
     */
    com.google.protobuf.ByteString
        getHeroesBytes(int index);

    /**
     * <pre>
     * ���ҵĶ���
     * </pre>
     *
     * <code>repeated string teams = 11;</code>
     */
    java.util.List<java.lang.String>
        getTeamsList();
    /**
     * <pre>
     * ���ҵĶ���
     * </pre>
     *
     * <code>repeated string teams = 11;</code>
     */
    int getTeamsCount();
    /**
     * <pre>
     * ���ҵĶ���
     * </pre>
     *
     * <code>repeated string teams = 11;</code>
     */
    java.lang.String getTeams(int index);
    /**
     * <pre>
     * ���ҵĶ���
     * </pre>
     *
     * <code>repeated string teams = 11;</code>
     */
    com.google.protobuf.ByteString
        getTeamsBytes(int index);

    /**
     * <pre>
     * �����еĽ���
     * </pre>
     *
     * <code>required int32 gold = 12;</code>
     */
    boolean hasGold();
    /**
     * <pre>
     * �����еĽ���
     * </pre>
     *
     * <code>required int32 gold = 12;</code>
     */
    int getGold();

    /**
     * <pre>
     * �����е���ʯ
     * </pre>
     *
     * <code>required int32 gem = 13;</code>
     */
    boolean hasGem();
    /**
     * <pre>
     * �����е���ʯ
     * </pre>
     *
     * <code>required int32 gem = 13;</code>
     */
    int getGem();

    /**
     * <pre>
     * ���ҵ�Կ��
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
     */
    boolean hasKeys();
    /**
     * <pre>
     * ���ҵ�Կ��
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
     */
    cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getKeys();
    /**
     * <pre>
     * ���ҵ�Կ��
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
     */
    cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder getKeysOrBuilder();
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.DAT_UserData}
   */
  public  static final class DAT_UserData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.DAT_UserData)
      DAT_UserDataOrBuilder {
    // Use DAT_UserData.newBuilder() to construct.
    private DAT_UserData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DAT_UserData() {
      uid_ = "";
      nickname_ = "";
      lv_ = 0;
      experience_ = 0;
      roleId_ = "";
      strength_ = 0;
      magic_ = 0;
      agility_ = 0;
      heroes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      teams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      gold_ = 0;
      gem_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DAT_UserData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              nickname_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lv_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              experience_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              roleId_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              strength_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              magic_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              agility_ = input.readInt32();
              break;
            }
            case 74: {
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder subBuilder = null;
              if (((bitField0_ & 0x00000100) == 0x00000100)) {
                subBuilder = elementProperty_.toBuilder();
              }
              elementProperty_ = input.readMessage(cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(elementProperty_);
                elementProperty_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000100;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                heroes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000200;
              }
              heroes_.add(bs);
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                teams_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000400;
              }
              teams_.add(bs);
              break;
            }
            case 96: {
              bitField0_ |= 0x00000200;
              gold_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000400;
              gem_ = input.readInt32();
              break;
            }
            case 114: {
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder subBuilder = null;
              if (((bitField0_ & 0x00000800) == 0x00000800)) {
                subBuilder = keys_.toBuilder();
              }
              keys_ = input.readMessage(cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(keys_);
                keys_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000800;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          heroes_ = heroes_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          teams_ = teams_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.DatUserData.internal_static_cn_wzj_netty_proto_DAT_UserData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.DatUserData.internal_static_cn_wzj_netty_proto_DAT_UserData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.DatUserData.DAT_UserData.class, cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * ����UID
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * ����UID
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * ����UID
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nickname_;
    /**
     * <pre>
     * �����ǳ�
     * </pre>
     *
     * <code>required string nickname = 2;</code>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * �����ǳ�
     * </pre>
     *
     * <code>required string nickname = 2;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * �����ǳ�
     * </pre>
     *
     * <code>required string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LV_FIELD_NUMBER = 3;
    private int lv_;
    /**
     * <pre>
     * ���ҵȼ�
     * </pre>
     *
     * <code>required int32 lv = 3;</code>
     */
    public boolean hasLv() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * ���ҵȼ�
     * </pre>
     *
     * <code>required int32 lv = 3;</code>
     */
    public int getLv() {
      return lv_;
    }

    public static final int EXPERIENCE_FIELD_NUMBER = 4;
    private int experience_;
    /**
     * <pre>
     * ����ֵ
     * </pre>
     *
     * <code>required int32 experience = 4;</code>
     */
    public boolean hasExperience() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * ����ֵ
     * </pre>
     *
     * <code>required int32 experience = 4;</code>
     */
    public int getExperience() {
      return experience_;
    }

    public static final int ROLEID_FIELD_NUMBER = 5;
    private volatile java.lang.Object roleId_;
    /**
     * <pre>
     * ���ҽ�ɫid
     * </pre>
     *
     * <code>required string roleId = 5;</code>
     */
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * ���ҽ�ɫid
     * </pre>
     *
     * <code>required string roleId = 5;</code>
     */
    public java.lang.String getRoleId() {
      java.lang.Object ref = roleId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          roleId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * ���ҽ�ɫid
     * </pre>
     *
     * <code>required string roleId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRoleIdBytes() {
      java.lang.Object ref = roleId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRENGTH_FIELD_NUMBER = 6;
    private int strength_;
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 strength = 6;</code>
     */
    public boolean hasStrength() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 strength = 6;</code>
     */
    public int getStrength() {
      return strength_;
    }

    public static final int MAGIC_FIELD_NUMBER = 7;
    private int magic_;
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magic = 7;</code>
     */
    public boolean hasMagic() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magic = 7;</code>
     */
    public int getMagic() {
      return magic_;
    }

    public static final int AGILITY_FIELD_NUMBER = 8;
    private int agility_;
    /**
     * <pre>
     * ���ݶ�
     * </pre>
     *
     * <code>required int32 agility = 8;</code>
     */
    public boolean hasAgility() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * ���ݶ�
     * </pre>
     *
     * <code>required int32 agility = 8;</code>
     */
    public int getAgility() {
      return agility_;
    }

    public static final int ELEMENTPROPERTY_FIELD_NUMBER = 9;
    private cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty elementProperty_;
    /**
     * <pre>
     * ����Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
     */
    public boolean hasElementProperty() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     * ����Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
     */
    public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getElementProperty() {
      return elementProperty_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance() : elementProperty_;
    }
    /**
     * <pre>
     * ����Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
     */
    public cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder getElementPropertyOrBuilder() {
      return elementProperty_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance() : elementProperty_;
    }

    public static final int HEROES_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList heroes_;
    /**
     * <pre>
     * ����ӵ�е�����Ӣ��
     * </pre>
     *
     * <code>repeated string heroes = 10;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHeroesList() {
      return heroes_;
    }
    /**
     * <pre>
     * ����ӵ�е�����Ӣ��
     * </pre>
     *
     * <code>repeated string heroes = 10;</code>
     */
    public int getHeroesCount() {
      return heroes_.size();
    }
    /**
     * <pre>
     * ����ӵ�е�����Ӣ��
     * </pre>
     *
     * <code>repeated string heroes = 10;</code>
     */
    public java.lang.String getHeroes(int index) {
      return heroes_.get(index);
    }
    /**
     * <pre>
     * ����ӵ�е�����Ӣ��
     * </pre>
     *
     * <code>repeated string heroes = 10;</code>
     */
    public com.google.protobuf.ByteString
        getHeroesBytes(int index) {
      return heroes_.getByteString(index);
    }

    public static final int TEAMS_FIELD_NUMBER = 11;
    private com.google.protobuf.LazyStringList teams_;
    /**
     * <pre>
     * ���ҵĶ���
     * </pre>
     *
     * <code>repeated string teams = 11;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTeamsList() {
      return teams_;
    }
    /**
     * <pre>
     * ���ҵĶ���
     * </pre>
     *
     * <code>repeated string teams = 11;</code>
     */
    public int getTeamsCount() {
      return teams_.size();
    }
    /**
     * <pre>
     * ���ҵĶ���
     * </pre>
     *
     * <code>repeated string teams = 11;</code>
     */
    public java.lang.String getTeams(int index) {
      return teams_.get(index);
    }
    /**
     * <pre>
     * ���ҵĶ���
     * </pre>
     *
     * <code>repeated string teams = 11;</code>
     */
    public com.google.protobuf.ByteString
        getTeamsBytes(int index) {
      return teams_.getByteString(index);
    }

    public static final int GOLD_FIELD_NUMBER = 12;
    private int gold_;
    /**
     * <pre>
     * �����еĽ���
     * </pre>
     *
     * <code>required int32 gold = 12;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     * �����еĽ���
     * </pre>
     *
     * <code>required int32 gold = 12;</code>
     */
    public int getGold() {
      return gold_;
    }

    public static final int GEM_FIELD_NUMBER = 13;
    private int gem_;
    /**
     * <pre>
     * �����е���ʯ
     * </pre>
     *
     * <code>required int32 gem = 13;</code>
     */
    public boolean hasGem() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <pre>
     * �����е���ʯ
     * </pre>
     *
     * <code>required int32 gem = 13;</code>
     */
    public int getGem() {
      return gem_;
    }

    public static final int KEYS_FIELD_NUMBER = 14;
    private cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty keys_;
    /**
     * <pre>
     * ���ҵ�Կ��
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
     */
    public boolean hasKeys() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <pre>
     * ���ҵ�Կ��
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
     */
    public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getKeys() {
      return keys_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance() : keys_;
    }
    /**
     * <pre>
     * ���ҵ�Կ��
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
     */
    public cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder getKeysOrBuilder() {
      return keys_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance() : keys_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExperience()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStrength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMagic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAgility()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElementProperty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKeys()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getElementProperty().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getKeys().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nickname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, lv_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, experience_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, roleId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, strength_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, magic_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, agility_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, getElementProperty());
      }
      for (int i = 0; i < heroes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, heroes_.getRaw(i));
      }
      for (int i = 0; i < teams_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, teams_.getRaw(i));
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(12, gold_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(13, gem_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeMessage(14, getKeys());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nickname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, lv_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, experience_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, roleId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, strength_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, magic_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, agility_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getElementProperty());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < heroes_.size(); i++) {
          dataSize += computeStringSizeNoTag(heroes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHeroesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < teams_.size(); i++) {
          dataSize += computeStringSizeNoTag(teams_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTeamsList().size();
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, gold_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, gem_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getKeys());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.DatUserData.DAT_UserData)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.DatUserData.DAT_UserData other = (cn.wzj.netty.proto.DatUserData.DAT_UserData) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && getUid()
            .equals(other.getUid());
      }
      result = result && (hasNickname() == other.hasNickname());
      if (hasNickname()) {
        result = result && getNickname()
            .equals(other.getNickname());
      }
      result = result && (hasLv() == other.hasLv());
      if (hasLv()) {
        result = result && (getLv()
            == other.getLv());
      }
      result = result && (hasExperience() == other.hasExperience());
      if (hasExperience()) {
        result = result && (getExperience()
            == other.getExperience());
      }
      result = result && (hasRoleId() == other.hasRoleId());
      if (hasRoleId()) {
        result = result && getRoleId()
            .equals(other.getRoleId());
      }
      result = result && (hasStrength() == other.hasStrength());
      if (hasStrength()) {
        result = result && (getStrength()
            == other.getStrength());
      }
      result = result && (hasMagic() == other.hasMagic());
      if (hasMagic()) {
        result = result && (getMagic()
            == other.getMagic());
      }
      result = result && (hasAgility() == other.hasAgility());
      if (hasAgility()) {
        result = result && (getAgility()
            == other.getAgility());
      }
      result = result && (hasElementProperty() == other.hasElementProperty());
      if (hasElementProperty()) {
        result = result && getElementProperty()
            .equals(other.getElementProperty());
      }
      result = result && getHeroesList()
          .equals(other.getHeroesList());
      result = result && getTeamsList()
          .equals(other.getTeamsList());
      result = result && (hasGold() == other.hasGold());
      if (hasGold()) {
        result = result && (getGold()
            == other.getGold());
      }
      result = result && (hasGem() == other.hasGem());
      if (hasGem()) {
        result = result && (getGem()
            == other.getGem());
      }
      result = result && (hasKeys() == other.hasKeys());
      if (hasKeys()) {
        result = result && getKeys()
            .equals(other.getKeys());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
      }
      if (hasNickname()) {
        hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
        hash = (53 * hash) + getNickname().hashCode();
      }
      if (hasLv()) {
        hash = (37 * hash) + LV_FIELD_NUMBER;
        hash = (53 * hash) + getLv();
      }
      if (hasExperience()) {
        hash = (37 * hash) + EXPERIENCE_FIELD_NUMBER;
        hash = (53 * hash) + getExperience();
      }
      if (hasRoleId()) {
        hash = (37 * hash) + ROLEID_FIELD_NUMBER;
        hash = (53 * hash) + getRoleId().hashCode();
      }
      if (hasStrength()) {
        hash = (37 * hash) + STRENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getStrength();
      }
      if (hasMagic()) {
        hash = (37 * hash) + MAGIC_FIELD_NUMBER;
        hash = (53 * hash) + getMagic();
      }
      if (hasAgility()) {
        hash = (37 * hash) + AGILITY_FIELD_NUMBER;
        hash = (53 * hash) + getAgility();
      }
      if (hasElementProperty()) {
        hash = (37 * hash) + ELEMENTPROPERTY_FIELD_NUMBER;
        hash = (53 * hash) + getElementProperty().hashCode();
      }
      if (getHeroesCount() > 0) {
        hash = (37 * hash) + HEROES_FIELD_NUMBER;
        hash = (53 * hash) + getHeroesList().hashCode();
      }
      if (getTeamsCount() > 0) {
        hash = (37 * hash) + TEAMS_FIELD_NUMBER;
        hash = (53 * hash) + getTeamsList().hashCode();
      }
      if (hasGold()) {
        hash = (37 * hash) + GOLD_FIELD_NUMBER;
        hash = (53 * hash) + getGold();
      }
      if (hasGem()) {
        hash = (37 * hash) + GEM_FIELD_NUMBER;
        hash = (53 * hash) + getGem();
      }
      if (hasKeys()) {
        hash = (37 * hash) + KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getKeys().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatUserData.DAT_UserData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.DatUserData.DAT_UserData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.DAT_UserData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.DAT_UserData)
        cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.DatUserData.internal_static_cn_wzj_netty_proto_DAT_UserData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.DatUserData.internal_static_cn_wzj_netty_proto_DAT_UserData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.DatUserData.DAT_UserData.class, cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.DatUserData.DAT_UserData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getElementPropertyFieldBuilder();
          getKeysFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        experience_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        roleId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        strength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        magic_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        agility_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (elementPropertyBuilder_ == null) {
          elementProperty_ = null;
        } else {
          elementPropertyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        heroes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        teams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        gem_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        if (keysBuilder_ == null) {
          keys_ = null;
        } else {
          keysBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.DatUserData.internal_static_cn_wzj_netty_proto_DAT_UserData_descriptor;
      }

      public cn.wzj.netty.proto.DatUserData.DAT_UserData getDefaultInstanceForType() {
        return cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance();
      }

      public cn.wzj.netty.proto.DatUserData.DAT_UserData build() {
        cn.wzj.netty.proto.DatUserData.DAT_UserData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.DatUserData.DAT_UserData buildPartial() {
        cn.wzj.netty.proto.DatUserData.DAT_UserData result = new cn.wzj.netty.proto.DatUserData.DAT_UserData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nickname_ = nickname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lv_ = lv_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.experience_ = experience_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.strength_ = strength_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.magic_ = magic_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.agility_ = agility_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (elementPropertyBuilder_ == null) {
          result.elementProperty_ = elementProperty_;
        } else {
          result.elementProperty_ = elementPropertyBuilder_.build();
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          heroes_ = heroes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.heroes_ = heroes_;
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          teams_ = teams_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.teams_ = teams_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000200;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000400;
        }
        result.gem_ = gem_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00000800;
        }
        if (keysBuilder_ == null) {
          result.keys_ = keys_;
        } else {
          result.keys_ = keysBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.DatUserData.DAT_UserData) {
          return mergeFrom((cn.wzj.netty.proto.DatUserData.DAT_UserData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.DatUserData.DAT_UserData other) {
        if (other == cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasNickname()) {
          bitField0_ |= 0x00000002;
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.hasLv()) {
          setLv(other.getLv());
        }
        if (other.hasExperience()) {
          setExperience(other.getExperience());
        }
        if (other.hasRoleId()) {
          bitField0_ |= 0x00000010;
          roleId_ = other.roleId_;
          onChanged();
        }
        if (other.hasStrength()) {
          setStrength(other.getStrength());
        }
        if (other.hasMagic()) {
          setMagic(other.getMagic());
        }
        if (other.hasAgility()) {
          setAgility(other.getAgility());
        }
        if (other.hasElementProperty()) {
          mergeElementProperty(other.getElementProperty());
        }
        if (!other.heroes_.isEmpty()) {
          if (heroes_.isEmpty()) {
            heroes_ = other.heroes_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureHeroesIsMutable();
            heroes_.addAll(other.heroes_);
          }
          onChanged();
        }
        if (!other.teams_.isEmpty()) {
          if (teams_.isEmpty()) {
            teams_ = other.teams_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureTeamsIsMutable();
            teams_.addAll(other.teams_);
          }
          onChanged();
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasGem()) {
          setGem(other.getGem());
        }
        if (other.hasKeys()) {
          mergeKeys(other.getKeys());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        if (!hasNickname()) {
          return false;
        }
        if (!hasLv()) {
          return false;
        }
        if (!hasExperience()) {
          return false;
        }
        if (!hasRoleId()) {
          return false;
        }
        if (!hasStrength()) {
          return false;
        }
        if (!hasMagic()) {
          return false;
        }
        if (!hasAgility()) {
          return false;
        }
        if (!hasElementProperty()) {
          return false;
        }
        if (!hasGold()) {
          return false;
        }
        if (!hasGem()) {
          return false;
        }
        if (!hasKeys()) {
          return false;
        }
        if (!getElementProperty().isInitialized()) {
          return false;
        }
        if (!getKeys().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.DatUserData.DAT_UserData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.DatUserData.DAT_UserData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * ����UID
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * ����UID
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ����UID
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ����UID
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����UID
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����UID
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <pre>
       * �����ǳ�
       * </pre>
       *
       * <code>required string nickname = 2;</code>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * �����ǳ�
       * </pre>
       *
       * <code>required string nickname = 2;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * �����ǳ�
       * </pre>
       *
       * <code>required string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * �����ǳ�
       * </pre>
       *
       * <code>required string nickname = 2;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �����ǳ�
       * </pre>
       *
       * <code>required string nickname = 2;</code>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �����ǳ�
       * </pre>
       *
       * <code>required string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickname_ = value;
        onChanged();
        return this;
      }

      private int lv_ ;
      /**
       * <pre>
       * ���ҵȼ�
       * </pre>
       *
       * <code>required int32 lv = 3;</code>
       */
      public boolean hasLv() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * ���ҵȼ�
       * </pre>
       *
       * <code>required int32 lv = 3;</code>
       */
      public int getLv() {
        return lv_;
      }
      /**
       * <pre>
       * ���ҵȼ�
       * </pre>
       *
       * <code>required int32 lv = 3;</code>
       */
      public Builder setLv(int value) {
        bitField0_ |= 0x00000004;
        lv_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���ҵȼ�
       * </pre>
       *
       * <code>required int32 lv = 3;</code>
       */
      public Builder clearLv() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lv_ = 0;
        onChanged();
        return this;
      }

      private int experience_ ;
      /**
       * <pre>
       * ����ֵ
       * </pre>
       *
       * <code>required int32 experience = 4;</code>
       */
      public boolean hasExperience() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * ����ֵ
       * </pre>
       *
       * <code>required int32 experience = 4;</code>
       */
      public int getExperience() {
        return experience_;
      }
      /**
       * <pre>
       * ����ֵ
       * </pre>
       *
       * <code>required int32 experience = 4;</code>
       */
      public Builder setExperience(int value) {
        bitField0_ |= 0x00000008;
        experience_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����ֵ
       * </pre>
       *
       * <code>required int32 experience = 4;</code>
       */
      public Builder clearExperience() {
        bitField0_ = (bitField0_ & ~0x00000008);
        experience_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object roleId_ = "";
      /**
       * <pre>
       * ���ҽ�ɫid
       * </pre>
       *
       * <code>required string roleId = 5;</code>
       */
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * ���ҽ�ɫid
       * </pre>
       *
       * <code>required string roleId = 5;</code>
       */
      public java.lang.String getRoleId() {
        java.lang.Object ref = roleId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            roleId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ���ҽ�ɫid
       * </pre>
       *
       * <code>required string roleId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRoleIdBytes() {
        java.lang.Object ref = roleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ���ҽ�ɫid
       * </pre>
       *
       * <code>required string roleId = 5;</code>
       */
      public Builder setRoleId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���ҽ�ɫid
       * </pre>
       *
       * <code>required string roleId = 5;</code>
       */
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        roleId_ = getDefaultInstance().getRoleId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���ҽ�ɫid
       * </pre>
       *
       * <code>required string roleId = 5;</code>
       */
      public Builder setRoleIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        roleId_ = value;
        onChanged();
        return this;
      }

      private int strength_ ;
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 strength = 6;</code>
       */
      public boolean hasStrength() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 strength = 6;</code>
       */
      public int getStrength() {
        return strength_;
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 strength = 6;</code>
       */
      public Builder setStrength(int value) {
        bitField0_ |= 0x00000020;
        strength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 strength = 6;</code>
       */
      public Builder clearStrength() {
        bitField0_ = (bitField0_ & ~0x00000020);
        strength_ = 0;
        onChanged();
        return this;
      }

      private int magic_ ;
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magic = 7;</code>
       */
      public boolean hasMagic() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magic = 7;</code>
       */
      public int getMagic() {
        return magic_;
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magic = 7;</code>
       */
      public Builder setMagic(int value) {
        bitField0_ |= 0x00000040;
        magic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magic = 7;</code>
       */
      public Builder clearMagic() {
        bitField0_ = (bitField0_ & ~0x00000040);
        magic_ = 0;
        onChanged();
        return this;
      }

      private int agility_ ;
      /**
       * <pre>
       * ���ݶ�
       * </pre>
       *
       * <code>required int32 agility = 8;</code>
       */
      public boolean hasAgility() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * ���ݶ�
       * </pre>
       *
       * <code>required int32 agility = 8;</code>
       */
      public int getAgility() {
        return agility_;
      }
      /**
       * <pre>
       * ���ݶ�
       * </pre>
       *
       * <code>required int32 agility = 8;</code>
       */
      public Builder setAgility(int value) {
        bitField0_ |= 0x00000080;
        agility_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���ݶ�
       * </pre>
       *
       * <code>required int32 agility = 8;</code>
       */
      public Builder clearAgility() {
        bitField0_ = (bitField0_ & ~0x00000080);
        agility_ = 0;
        onChanged();
        return this;
      }

      private cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty elementProperty_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty, cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder> elementPropertyBuilder_;
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      public boolean hasElementProperty() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getElementProperty() {
        if (elementPropertyBuilder_ == null) {
          return elementProperty_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance() : elementProperty_;
        } else {
          return elementPropertyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      public Builder setElementProperty(cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty value) {
        if (elementPropertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          elementProperty_ = value;
          onChanged();
        } else {
          elementPropertyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      public Builder setElementProperty(
          cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder builderForValue) {
        if (elementPropertyBuilder_ == null) {
          elementProperty_ = builderForValue.build();
          onChanged();
        } else {
          elementPropertyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      public Builder mergeElementProperty(cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty value) {
        if (elementPropertyBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              elementProperty_ != null &&
              elementProperty_ != cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance()) {
            elementProperty_ =
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.newBuilder(elementProperty_).mergeFrom(value).buildPartial();
          } else {
            elementProperty_ = value;
          }
          onChanged();
        } else {
          elementPropertyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      public Builder clearElementProperty() {
        if (elementPropertyBuilder_ == null) {
          elementProperty_ = null;
          onChanged();
        } else {
          elementPropertyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder getElementPropertyBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getElementPropertyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder getElementPropertyOrBuilder() {
        if (elementPropertyBuilder_ != null) {
          return elementPropertyBuilder_.getMessageOrBuilder();
        } else {
          return elementProperty_ == null ?
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance() : elementProperty_;
        }
      }
      /**
       * <pre>
       * ����Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty elementProperty = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty, cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder> 
          getElementPropertyFieldBuilder() {
        if (elementPropertyBuilder_ == null) {
          elementPropertyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty, cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder>(
                  getElementProperty(),
                  getParentForChildren(),
                  isClean());
          elementProperty_ = null;
        }
        return elementPropertyBuilder_;
      }

      private com.google.protobuf.LazyStringList heroes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHeroesIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          heroes_ = new com.google.protobuf.LazyStringArrayList(heroes_);
          bitField0_ |= 0x00000200;
         }
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHeroesList() {
        return heroes_.getUnmodifiableView();
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public int getHeroesCount() {
        return heroes_.size();
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public java.lang.String getHeroes(int index) {
        return heroes_.get(index);
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public com.google.protobuf.ByteString
          getHeroesBytes(int index) {
        return heroes_.getByteString(index);
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public Builder setHeroes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeroesIsMutable();
        heroes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public Builder addHeroes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeroesIsMutable();
        heroes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public Builder addAllHeroes(
          java.lang.Iterable<java.lang.String> values) {
        ensureHeroesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, heroes_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public Builder clearHeroes() {
        heroes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����ӵ�е�����Ӣ��
       * </pre>
       *
       * <code>repeated string heroes = 10;</code>
       */
      public Builder addHeroesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeroesIsMutable();
        heroes_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList teams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTeamsIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          teams_ = new com.google.protobuf.LazyStringArrayList(teams_);
          bitField0_ |= 0x00000400;
         }
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTeamsList() {
        return teams_.getUnmodifiableView();
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public int getTeamsCount() {
        return teams_.size();
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public java.lang.String getTeams(int index) {
        return teams_.get(index);
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public com.google.protobuf.ByteString
          getTeamsBytes(int index) {
        return teams_.getByteString(index);
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public Builder setTeams(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTeamsIsMutable();
        teams_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public Builder addTeams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTeamsIsMutable();
        teams_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public Builder addAllTeams(
          java.lang.Iterable<java.lang.String> values) {
        ensureTeamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, teams_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public Builder clearTeams() {
        teams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���ҵĶ���
       * </pre>
       *
       * <code>repeated string teams = 11;</code>
       */
      public Builder addTeamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTeamsIsMutable();
        teams_.add(value);
        onChanged();
        return this;
      }

      private int gold_ ;
      /**
       * <pre>
       * �����еĽ���
       * </pre>
       *
       * <code>required int32 gold = 12;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <pre>
       * �����еĽ���
       * </pre>
       *
       * <code>required int32 gold = 12;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <pre>
       * �����еĽ���
       * </pre>
       *
       * <code>required int32 gold = 12;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000800;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �����еĽ���
       * </pre>
       *
       * <code>required int32 gold = 12;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000800);
        gold_ = 0;
        onChanged();
        return this;
      }

      private int gem_ ;
      /**
       * <pre>
       * �����е���ʯ
       * </pre>
       *
       * <code>required int32 gem = 13;</code>
       */
      public boolean hasGem() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <pre>
       * �����е���ʯ
       * </pre>
       *
       * <code>required int32 gem = 13;</code>
       */
      public int getGem() {
        return gem_;
      }
      /**
       * <pre>
       * �����е���ʯ
       * </pre>
       *
       * <code>required int32 gem = 13;</code>
       */
      public Builder setGem(int value) {
        bitField0_ |= 0x00001000;
        gem_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �����е���ʯ
       * </pre>
       *
       * <code>required int32 gem = 13;</code>
       */
      public Builder clearGem() {
        bitField0_ = (bitField0_ & ~0x00001000);
        gem_ = 0;
        onChanged();
        return this;
      }

      private cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty keys_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty, cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder> keysBuilder_;
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      public boolean hasKeys() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getKeys() {
        if (keysBuilder_ == null) {
          return keys_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance() : keys_;
        } else {
          return keysBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      public Builder setKeys(cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty value) {
        if (keysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          keys_ = value;
          onChanged();
        } else {
          keysBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      public Builder setKeys(
          cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder builderForValue) {
        if (keysBuilder_ == null) {
          keys_ = builderForValue.build();
          onChanged();
        } else {
          keysBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      public Builder mergeKeys(cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty value) {
        if (keysBuilder_ == null) {
          if (((bitField0_ & 0x00002000) == 0x00002000) &&
              keys_ != null &&
              keys_ != cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance()) {
            keys_ =
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.newBuilder(keys_).mergeFrom(value).buildPartial();
          } else {
            keys_ = value;
          }
          onChanged();
        } else {
          keysBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      public Builder clearKeys() {
        if (keysBuilder_ == null) {
          keys_ = null;
          onChanged();
        } else {
          keysBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder getKeysBuilder() {
        bitField0_ |= 0x00002000;
        onChanged();
        return getKeysFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder getKeysOrBuilder() {
        if (keysBuilder_ != null) {
          return keysBuilder_.getMessageOrBuilder();
        } else {
          return keys_ == null ?
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance() : keys_;
        }
      }
      /**
       * <pre>
       * ���ҵ�Կ��
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementProperty keys = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty, cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder> 
          getKeysFieldBuilder() {
        if (keysBuilder_ == null) {
          keysBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty, cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder>(
                  getKeys(),
                  getParentForChildren(),
                  isClean());
          keys_ = null;
        }
        return keysBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.DAT_UserData)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.DAT_UserData)
    private static final cn.wzj.netty.proto.DatUserData.DAT_UserData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.DatUserData.DAT_UserData();
    }

    public static cn.wzj.netty.proto.DatUserData.DAT_UserData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DAT_UserData>
        PARSER = new com.google.protobuf.AbstractParser<DAT_UserData>() {
      public DAT_UserData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DAT_UserData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DAT_UserData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DAT_UserData> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.DatUserData.DAT_UserData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_DAT_UserData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_DAT_UserData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Dat_UserData.proto\022\022cn.wzj.netty.proto" +
      "\032\021Dat_General.proto\"\302\002\n\014DAT_UserData\022\013\n\003" +
      "uid\030\001 \002(\t\022\020\n\010nickname\030\002 \002(\t\022\n\n\002lv\030\003 \002(\005\022" +
      "\022\n\nexperience\030\004 \002(\005\022\016\n\006roleId\030\005 \002(\t\022\020\n\010s" +
      "trength\030\006 \002(\005\022\r\n\005magic\030\007 \002(\005\022\017\n\007agility\030" +
      "\010 \002(\005\022@\n\017elementProperty\030\t \002(\0132\'.cn.wzj." +
      "netty.proto.DAT_ElementProperty\022\016\n\006heroe" +
      "s\030\n \003(\t\022\r\n\005teams\030\013 \003(\t\022\014\n\004gold\030\014 \002(\005\022\013\n\003" +
      "gem\030\r \002(\005\0225\n\004keys\030\016 \002(\0132\'.cn.wzj.netty.p" +
      "roto.DAT_ElementProperty"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.wzj.netty.proto.DatGeneral.getDescriptor(),
        }, assigner);
    internal_static_cn_wzj_netty_proto_DAT_UserData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_wzj_netty_proto_DAT_UserData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_DAT_UserData_descriptor,
        new java.lang.String[] { "Uid", "Nickname", "Lv", "Experience", "RoleId", "Strength", "Magic", "Agility", "ElementProperty", "Heroes", "Teams", "Gold", "Gem", "Keys", });
    cn.wzj.netty.proto.DatGeneral.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
