// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dat_General.proto

package cn.wzj.netty.proto;

public final class DatGeneral {
  private DatGeneral() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DAT_ElementPropertyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.DAT_ElementProperty)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 air = 1;</code>
     */
    boolean hasAir();
    /**
     * <code>required int32 air = 1;</code>
     */
    int getAir();

    /**
     * <code>required int32 water = 2;</code>
     */
    boolean hasWater();
    /**
     * <code>required int32 water = 2;</code>
     */
    int getWater();

    /**
     * <code>required int32 fire = 3;</code>
     */
    boolean hasFire();
    /**
     * <code>required int32 fire = 3;</code>
     */
    int getFire();

    /**
     * <code>required int32 earth = 4;</code>
     */
    boolean hasEarth();
    /**
     * <code>required int32 earth = 4;</code>
     */
    int getEarth();
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.DAT_ElementProperty}
   */
  public  static final class DAT_ElementProperty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.DAT_ElementProperty)
      DAT_ElementPropertyOrBuilder {
    // Use DAT_ElementProperty.newBuilder() to construct.
    private DAT_ElementProperty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DAT_ElementProperty() {
      air_ = 0;
      water_ = 0;
      fire_ = 0;
      earth_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DAT_ElementProperty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              air_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              water_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fire_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              earth_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementProperty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementProperty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.class, cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder.class);
    }

    private int bitField0_;
    public static final int AIR_FIELD_NUMBER = 1;
    private int air_;
    /**
     * <code>required int32 air = 1;</code>
     */
    public boolean hasAir() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 air = 1;</code>
     */
    public int getAir() {
      return air_;
    }

    public static final int WATER_FIELD_NUMBER = 2;
    private int water_;
    /**
     * <code>required int32 water = 2;</code>
     */
    public boolean hasWater() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 water = 2;</code>
     */
    public int getWater() {
      return water_;
    }

    public static final int FIRE_FIELD_NUMBER = 3;
    private int fire_;
    /**
     * <code>required int32 fire = 3;</code>
     */
    public boolean hasFire() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 fire = 3;</code>
     */
    public int getFire() {
      return fire_;
    }

    public static final int EARTH_FIELD_NUMBER = 4;
    private int earth_;
    /**
     * <code>required int32 earth = 4;</code>
     */
    public boolean hasEarth() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 earth = 4;</code>
     */
    public int getEarth() {
      return earth_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWater()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFire()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEarth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, air_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, water_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, fire_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, earth_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, air_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, water_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fire_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, earth_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty other = (cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty) obj;

      boolean result = true;
      result = result && (hasAir() == other.hasAir());
      if (hasAir()) {
        result = result && (getAir()
            == other.getAir());
      }
      result = result && (hasWater() == other.hasWater());
      if (hasWater()) {
        result = result && (getWater()
            == other.getWater());
      }
      result = result && (hasFire() == other.hasFire());
      if (hasFire()) {
        result = result && (getFire()
            == other.getFire());
      }
      result = result && (hasEarth() == other.hasEarth());
      if (hasEarth()) {
        result = result && (getEarth()
            == other.getEarth());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAir()) {
        hash = (37 * hash) + AIR_FIELD_NUMBER;
        hash = (53 * hash) + getAir();
      }
      if (hasWater()) {
        hash = (37 * hash) + WATER_FIELD_NUMBER;
        hash = (53 * hash) + getWater();
      }
      if (hasFire()) {
        hash = (37 * hash) + FIRE_FIELD_NUMBER;
        hash = (53 * hash) + getFire();
      }
      if (hasEarth()) {
        hash = (37 * hash) + EARTH_FIELD_NUMBER;
        hash = (53 * hash) + getEarth();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.DAT_ElementProperty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.DAT_ElementProperty)
        cn.wzj.netty.proto.DatGeneral.DAT_ElementPropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementProperty_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementProperty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.class, cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        air_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        water_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        fire_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        earth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementProperty_descriptor;
      }

      public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getDefaultInstanceForType() {
        return cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance();
      }

      public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty build() {
        cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty buildPartial() {
        cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty result = new cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.air_ = air_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.water_ = water_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fire_ = fire_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.earth_ = earth_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty) {
          return mergeFrom((cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty other) {
        if (other == cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty.getDefaultInstance()) return this;
        if (other.hasAir()) {
          setAir(other.getAir());
        }
        if (other.hasWater()) {
          setWater(other.getWater());
        }
        if (other.hasFire()) {
          setFire(other.getFire());
        }
        if (other.hasEarth()) {
          setEarth(other.getEarth());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAir()) {
          return false;
        }
        if (!hasWater()) {
          return false;
        }
        if (!hasFire()) {
          return false;
        }
        if (!hasEarth()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int air_ ;
      /**
       * <code>required int32 air = 1;</code>
       */
      public boolean hasAir() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 air = 1;</code>
       */
      public int getAir() {
        return air_;
      }
      /**
       * <code>required int32 air = 1;</code>
       */
      public Builder setAir(int value) {
        bitField0_ |= 0x00000001;
        air_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 air = 1;</code>
       */
      public Builder clearAir() {
        bitField0_ = (bitField0_ & ~0x00000001);
        air_ = 0;
        onChanged();
        return this;
      }

      private int water_ ;
      /**
       * <code>required int32 water = 2;</code>
       */
      public boolean hasWater() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 water = 2;</code>
       */
      public int getWater() {
        return water_;
      }
      /**
       * <code>required int32 water = 2;</code>
       */
      public Builder setWater(int value) {
        bitField0_ |= 0x00000002;
        water_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 water = 2;</code>
       */
      public Builder clearWater() {
        bitField0_ = (bitField0_ & ~0x00000002);
        water_ = 0;
        onChanged();
        return this;
      }

      private int fire_ ;
      /**
       * <code>required int32 fire = 3;</code>
       */
      public boolean hasFire() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 fire = 3;</code>
       */
      public int getFire() {
        return fire_;
      }
      /**
       * <code>required int32 fire = 3;</code>
       */
      public Builder setFire(int value) {
        bitField0_ |= 0x00000004;
        fire_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 fire = 3;</code>
       */
      public Builder clearFire() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fire_ = 0;
        onChanged();
        return this;
      }

      private int earth_ ;
      /**
       * <code>required int32 earth = 4;</code>
       */
      public boolean hasEarth() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 earth = 4;</code>
       */
      public int getEarth() {
        return earth_;
      }
      /**
       * <code>required int32 earth = 4;</code>
       */
      public Builder setEarth(int value) {
        bitField0_ |= 0x00000008;
        earth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 earth = 4;</code>
       */
      public Builder clearEarth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        earth_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.DAT_ElementProperty)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.DAT_ElementProperty)
    private static final cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty();
    }

    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DAT_ElementProperty>
        PARSER = new com.google.protobuf.AbstractParser<DAT_ElementProperty>() {
      public DAT_ElementProperty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DAT_ElementProperty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DAT_ElementProperty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DAT_ElementProperty> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.DatGeneral.DAT_ElementProperty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DAT_ElementTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.DAT_ElementType)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.DAT_ElementType}
   */
  public  static final class DAT_ElementType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.DAT_ElementType)
      DAT_ElementTypeOrBuilder {
    // Use DAT_ElementType.newBuilder() to construct.
    private DAT_ElementType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DAT_ElementType() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DAT_ElementType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType.class, cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder.class);
    }

    /**
     * Protobuf enum {@code cn.wzj.netty.proto.DAT_ElementType.ele}
     */
    public enum ele
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Air = 0;</code>
       */
      Air(0),
      /**
       * <code>Water = 1;</code>
       */
      Water(1),
      /**
       * <code>Fire = 2;</code>
       */
      Fire(2),
      /**
       * <code>Earth = 3;</code>
       */
      Earth(3),
      ;

      /**
       * <code>Air = 0;</code>
       */
      public static final int Air_VALUE = 0;
      /**
       * <code>Water = 1;</code>
       */
      public static final int Water_VALUE = 1;
      /**
       * <code>Fire = 2;</code>
       */
      public static final int Fire_VALUE = 2;
      /**
       * <code>Earth = 3;</code>
       */
      public static final int Earth_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ele valueOf(int value) {
        return forNumber(value);
      }

      public static ele forNumber(int value) {
        switch (value) {
          case 0: return Air;
          case 1: return Water;
          case 2: return Fire;
          case 3: return Earth;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ele>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ele> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ele>() {
              public ele findValueByNumber(int number) {
                return ele.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDescriptor().getEnumTypes().get(0);
      }

      private static final ele[] VALUES = values();

      public static ele valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ele(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.wzj.netty.proto.DAT_ElementType.ele)
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.DatGeneral.DAT_ElementType)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.DatGeneral.DAT_ElementType other = (cn.wzj.netty.proto.DatGeneral.DAT_ElementType) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.DatGeneral.DAT_ElementType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.DAT_ElementType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.DAT_ElementType)
        cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.DatGeneral.DAT_ElementType.class, cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.DatGeneral.DAT_ElementType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.DatGeneral.internal_static_cn_wzj_netty_proto_DAT_ElementType_descriptor;
      }

      public cn.wzj.netty.proto.DatGeneral.DAT_ElementType getDefaultInstanceForType() {
        return cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance();
      }

      public cn.wzj.netty.proto.DatGeneral.DAT_ElementType build() {
        cn.wzj.netty.proto.DatGeneral.DAT_ElementType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.DatGeneral.DAT_ElementType buildPartial() {
        cn.wzj.netty.proto.DatGeneral.DAT_ElementType result = new cn.wzj.netty.proto.DatGeneral.DAT_ElementType(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.DatGeneral.DAT_ElementType) {
          return mergeFrom((cn.wzj.netty.proto.DatGeneral.DAT_ElementType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.DatGeneral.DAT_ElementType other) {
        if (other == cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.DatGeneral.DAT_ElementType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.DatGeneral.DAT_ElementType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.DAT_ElementType)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.DAT_ElementType)
    private static final cn.wzj.netty.proto.DatGeneral.DAT_ElementType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.DatGeneral.DAT_ElementType();
    }

    public static cn.wzj.netty.proto.DatGeneral.DAT_ElementType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DAT_ElementType>
        PARSER = new com.google.protobuf.AbstractParser<DAT_ElementType>() {
      public DAT_ElementType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DAT_ElementType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DAT_ElementType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DAT_ElementType> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.DatGeneral.DAT_ElementType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_DAT_ElementProperty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_DAT_ElementProperty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_DAT_ElementType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_DAT_ElementType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Dat_General.proto\022\022cn.wzj.netty.proto\"" +
      "N\n\023DAT_ElementProperty\022\013\n\003air\030\001 \002(\005\022\r\n\005w" +
      "ater\030\002 \002(\005\022\014\n\004fire\030\003 \002(\005\022\r\n\005earth\030\004 \002(\005\"" +
      "A\n\017DAT_ElementType\".\n\003ele\022\007\n\003Air\020\000\022\t\n\005Wa" +
      "ter\020\001\022\010\n\004Fire\020\002\022\t\n\005Earth\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_wzj_netty_proto_DAT_ElementProperty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_wzj_netty_proto_DAT_ElementProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_DAT_ElementProperty_descriptor,
        new java.lang.String[] { "Air", "Water", "Fire", "Earth", });
    internal_static_cn_wzj_netty_proto_DAT_ElementType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_wzj_netty_proto_DAT_ElementType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_DAT_ElementType_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
