// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dat_HeroData.proto

package cn.wzj.netty.proto;

public final class DatHeroData {
  private DatHeroData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DAT_HeroDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.DAT_HeroData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Ψһid �������ݿ���¼
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <pre>
     * Ψһid �������ݿ���¼
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <pre>
     * Ψһid �������ݿ���¼
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * �ȼ�
     * </pre>
     *
     * <code>required int32 lv = 3;</code>
     */
    boolean hasLv();
    /**
     * <pre>
     * �ȼ�
     * </pre>
     *
     * <code>required int32 lv = 3;</code>
     */
    int getLv();

    /**
     * <pre>
     * ����
     * </pre>
     *
     * <code>required int32 experience = 4;</code>
     */
    boolean hasExperience();
    /**
     * <pre>
     * ����
     * </pre>
     *
     * <code>required int32 experience = 4;</code>
     */
    int getExperience();

    /**
     * <pre>
     * Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
     */
    boolean hasElementType();
    /**
     * <pre>
     * Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
     */
    cn.wzj.netty.proto.DatGeneral.DAT_ElementType getElementType();
    /**
     * <pre>
     * Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
     */
    cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder getElementTypeOrBuilder();

    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 physicalAttack = 6;</code>
     */
    boolean hasPhysicalAttack();
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 physicalAttack = 6;</code>
     */
    int getPhysicalAttack();

    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 physicalDefence = 7;</code>
     */
    boolean hasPhysicalDefence();
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 physicalDefence = 7;</code>
     */
    int getPhysicalDefence();

    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magicalAttack = 8;</code>
     */
    boolean hasMagicalAttack();
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magicalAttack = 8;</code>
     */
    int getMagicalAttack();

    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magicalDefence = 9;</code>
     */
    boolean hasMagicalDefence();
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magicalDefence = 9;</code>
     */
    int getMagicalDefence();

    /**
     * <pre>
     * ���Թ���
     * </pre>
     *
     * <code>required int32 absoluteAttack = 10;</code>
     */
    boolean hasAbsoluteAttack();
    /**
     * <pre>
     * ���Թ���
     * </pre>
     *
     * <code>required int32 absoluteAttack = 10;</code>
     */
    int getAbsoluteAttack();

    /**
     * <pre>
     * �ж��ٶ�
     * </pre>
     *
     * <code>required int32 speed = 11;</code>
     */
    boolean hasSpeed();
    /**
     * <pre>
     * �ж��ٶ�
     * </pre>
     *
     * <code>required int32 speed = 11;</code>
     */
    int getSpeed();

    /**
     * <pre>
     * �ƶ�������
     * </pre>
     *
     * <code>required int32 move = 12;</code>
     */
    boolean hasMove();
    /**
     * <pre>
     * �ƶ�������
     * </pre>
     *
     * <code>required int32 move = 12;</code>
     */
    int getMove();

    /**
     * <pre>
     *������Χ
     * </pre>
     *
     * <code>required int32 attackRange = 13;</code>
     */
    boolean hasAttackRange();
    /**
     * <pre>
     *������Χ
     * </pre>
     *
     * <code>required int32 attackRange = 13;</code>
     */
    int getAttackRange();

    /**
     * <pre>
     * ����ֵ
     * </pre>
     *
     * <code>required int32 hp = 14;</code>
     */
    boolean hasHp();
    /**
     * <pre>
     * ����ֵ
     * </pre>
     *
     * <code>required int32 hp = 14;</code>
     */
    int getHp();

    /**
     * <pre>
     * Ӣ�۵ļ����б�
     * </pre>
     *
     * <code>repeated string skills = 15;</code>
     */
    java.util.List<java.lang.String>
        getSkillsList();
    /**
     * <pre>
     * Ӣ�۵ļ����б�
     * </pre>
     *
     * <code>repeated string skills = 15;</code>
     */
    int getSkillsCount();
    /**
     * <pre>
     * Ӣ�۵ļ����б�
     * </pre>
     *
     * <code>repeated string skills = 15;</code>
     */
    java.lang.String getSkills(int index);
    /**
     * <pre>
     * Ӣ�۵ļ����б�
     * </pre>
     *
     * <code>repeated string skills = 15;</code>
     */
    com.google.protobuf.ByteString
        getSkillsBytes(int index);
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.DAT_HeroData}
   */
  public  static final class DAT_HeroData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.DAT_HeroData)
      DAT_HeroDataOrBuilder {
    // Use DAT_HeroData.newBuilder() to construct.
    private DAT_HeroData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DAT_HeroData() {
      uid_ = "";
      id_ = "";
      lv_ = 0;
      experience_ = 0;
      physicalAttack_ = 0;
      physicalDefence_ = 0;
      magicalAttack_ = 0;
      magicalDefence_ = 0;
      absoluteAttack_ = 0;
      speed_ = 0;
      move_ = 0;
      attackRange_ = 0;
      hp_ = 0;
      skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DAT_HeroData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              id_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lv_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              experience_ = input.readInt32();
              break;
            }
            case 42: {
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = elementType_.toBuilder();
              }
              elementType_ = input.readMessage(cn.wzj.netty.proto.DatGeneral.DAT_ElementType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(elementType_);
                elementType_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              physicalAttack_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              physicalDefence_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              magicalAttack_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              magicalDefence_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              absoluteAttack_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              speed_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              move_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              attackRange_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              hp_ = input.readInt32();
              break;
            }
            case 122: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
                skills_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00004000;
              }
              skills_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
          skills_ = skills_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.DatHeroData.internal_static_cn_wzj_netty_proto_DAT_HeroData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.DatHeroData.internal_static_cn_wzj_netty_proto_DAT_HeroData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.DatHeroData.DAT_HeroData.class, cn.wzj.netty.proto.DatHeroData.DAT_HeroData.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * Ψһid �������ݿ���¼
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Ψһid �������ݿ���¼
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Ψһid �������ݿ���¼
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LV_FIELD_NUMBER = 3;
    private int lv_;
    /**
     * <pre>
     * �ȼ�
     * </pre>
     *
     * <code>required int32 lv = 3;</code>
     */
    public boolean hasLv() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * �ȼ�
     * </pre>
     *
     * <code>required int32 lv = 3;</code>
     */
    public int getLv() {
      return lv_;
    }

    public static final int EXPERIENCE_FIELD_NUMBER = 4;
    private int experience_;
    /**
     * <pre>
     * ����
     * </pre>
     *
     * <code>required int32 experience = 4;</code>
     */
    public boolean hasExperience() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * ����
     * </pre>
     *
     * <code>required int32 experience = 4;</code>
     */
    public int getExperience() {
      return experience_;
    }

    public static final int ELEMENTTYPE_FIELD_NUMBER = 5;
    private cn.wzj.netty.proto.DatGeneral.DAT_ElementType elementType_;
    /**
     * <pre>
     * Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
     */
    public boolean hasElementType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
     */
    public cn.wzj.netty.proto.DatGeneral.DAT_ElementType getElementType() {
      return elementType_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance() : elementType_;
    }
    /**
     * <pre>
     * Ԫ������
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
     */
    public cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder getElementTypeOrBuilder() {
      return elementType_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance() : elementType_;
    }

    public static final int PHYSICALATTACK_FIELD_NUMBER = 6;
    private int physicalAttack_;
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 physicalAttack = 6;</code>
     */
    public boolean hasPhysicalAttack() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 physicalAttack = 6;</code>
     */
    public int getPhysicalAttack() {
      return physicalAttack_;
    }

    public static final int PHYSICALDEFENCE_FIELD_NUMBER = 7;
    private int physicalDefence_;
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 physicalDefence = 7;</code>
     */
    public boolean hasPhysicalDefence() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>required int32 physicalDefence = 7;</code>
     */
    public int getPhysicalDefence() {
      return physicalDefence_;
    }

    public static final int MAGICALATTACK_FIELD_NUMBER = 8;
    private int magicalAttack_;
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magicalAttack = 8;</code>
     */
    public boolean hasMagicalAttack() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magicalAttack = 8;</code>
     */
    public int getMagicalAttack() {
      return magicalAttack_;
    }

    public static final int MAGICALDEFENCE_FIELD_NUMBER = 9;
    private int magicalDefence_;
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magicalDefence = 9;</code>
     */
    public boolean hasMagicalDefence() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     * ħ������
     * </pre>
     *
     * <code>required int32 magicalDefence = 9;</code>
     */
    public int getMagicalDefence() {
      return magicalDefence_;
    }

    public static final int ABSOLUTEATTACK_FIELD_NUMBER = 10;
    private int absoluteAttack_;
    /**
     * <pre>
     * ���Թ���
     * </pre>
     *
     * <code>required int32 absoluteAttack = 10;</code>
     */
    public boolean hasAbsoluteAttack() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     * ���Թ���
     * </pre>
     *
     * <code>required int32 absoluteAttack = 10;</code>
     */
    public int getAbsoluteAttack() {
      return absoluteAttack_;
    }

    public static final int SPEED_FIELD_NUMBER = 11;
    private int speed_;
    /**
     * <pre>
     * �ж��ٶ�
     * </pre>
     *
     * <code>required int32 speed = 11;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <pre>
     * �ж��ٶ�
     * </pre>
     *
     * <code>required int32 speed = 11;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    public static final int MOVE_FIELD_NUMBER = 12;
    private int move_;
    /**
     * <pre>
     * �ƶ�������
     * </pre>
     *
     * <code>required int32 move = 12;</code>
     */
    public boolean hasMove() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <pre>
     * �ƶ�������
     * </pre>
     *
     * <code>required int32 move = 12;</code>
     */
    public int getMove() {
      return move_;
    }

    public static final int ATTACKRANGE_FIELD_NUMBER = 13;
    private int attackRange_;
    /**
     * <pre>
     *������Χ
     * </pre>
     *
     * <code>required int32 attackRange = 13;</code>
     */
    public boolean hasAttackRange() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <pre>
     *������Χ
     * </pre>
     *
     * <code>required int32 attackRange = 13;</code>
     */
    public int getAttackRange() {
      return attackRange_;
    }

    public static final int HP_FIELD_NUMBER = 14;
    private int hp_;
    /**
     * <pre>
     * ����ֵ
     * </pre>
     *
     * <code>required int32 hp = 14;</code>
     */
    public boolean hasHp() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <pre>
     * ����ֵ
     * </pre>
     *
     * <code>required int32 hp = 14;</code>
     */
    public int getHp() {
      return hp_;
    }

    public static final int SKILLS_FIELD_NUMBER = 15;
    private com.google.protobuf.LazyStringList skills_;
    /**
     * <pre>
     * Ӣ�۵ļ����б�
     * </pre>
     *
     * <code>repeated string skills = 15;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSkillsList() {
      return skills_;
    }
    /**
     * <pre>
     * Ӣ�۵ļ����б�
     * </pre>
     *
     * <code>repeated string skills = 15;</code>
     */
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <pre>
     * Ӣ�۵ļ����б�
     * </pre>
     *
     * <code>repeated string skills = 15;</code>
     */
    public java.lang.String getSkills(int index) {
      return skills_.get(index);
    }
    /**
     * <pre>
     * Ӣ�۵ļ����б�
     * </pre>
     *
     * <code>repeated string skills = 15;</code>
     */
    public com.google.protobuf.ByteString
        getSkillsBytes(int index) {
      return skills_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExperience()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElementType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhysicalAttack()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhysicalDefence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMagicalAttack()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMagicalDefence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAbsoluteAttack()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMove()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttackRange()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, lv_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, experience_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getElementType());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, physicalAttack_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, physicalDefence_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, magicalAttack_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, magicalDefence_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, absoluteAttack_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, speed_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, move_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, attackRange_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, hp_);
      }
      for (int i = 0; i < skills_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, skills_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, lv_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, experience_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getElementType());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, physicalAttack_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, physicalDefence_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, magicalAttack_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, magicalDefence_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, absoluteAttack_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, speed_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, move_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, attackRange_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, hp_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < skills_.size(); i++) {
          dataSize += computeStringSizeNoTag(skills_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSkillsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.DatHeroData.DAT_HeroData)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.DatHeroData.DAT_HeroData other = (cn.wzj.netty.proto.DatHeroData.DAT_HeroData) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && getUid()
            .equals(other.getUid());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasLv() == other.hasLv());
      if (hasLv()) {
        result = result && (getLv()
            == other.getLv());
      }
      result = result && (hasExperience() == other.hasExperience());
      if (hasExperience()) {
        result = result && (getExperience()
            == other.getExperience());
      }
      result = result && (hasElementType() == other.hasElementType());
      if (hasElementType()) {
        result = result && getElementType()
            .equals(other.getElementType());
      }
      result = result && (hasPhysicalAttack() == other.hasPhysicalAttack());
      if (hasPhysicalAttack()) {
        result = result && (getPhysicalAttack()
            == other.getPhysicalAttack());
      }
      result = result && (hasPhysicalDefence() == other.hasPhysicalDefence());
      if (hasPhysicalDefence()) {
        result = result && (getPhysicalDefence()
            == other.getPhysicalDefence());
      }
      result = result && (hasMagicalAttack() == other.hasMagicalAttack());
      if (hasMagicalAttack()) {
        result = result && (getMagicalAttack()
            == other.getMagicalAttack());
      }
      result = result && (hasMagicalDefence() == other.hasMagicalDefence());
      if (hasMagicalDefence()) {
        result = result && (getMagicalDefence()
            == other.getMagicalDefence());
      }
      result = result && (hasAbsoluteAttack() == other.hasAbsoluteAttack());
      if (hasAbsoluteAttack()) {
        result = result && (getAbsoluteAttack()
            == other.getAbsoluteAttack());
      }
      result = result && (hasSpeed() == other.hasSpeed());
      if (hasSpeed()) {
        result = result && (getSpeed()
            == other.getSpeed());
      }
      result = result && (hasMove() == other.hasMove());
      if (hasMove()) {
        result = result && (getMove()
            == other.getMove());
      }
      result = result && (hasAttackRange() == other.hasAttackRange());
      if (hasAttackRange()) {
        result = result && (getAttackRange()
            == other.getAttackRange());
      }
      result = result && (hasHp() == other.hasHp());
      if (hasHp()) {
        result = result && (getHp()
            == other.getHp());
      }
      result = result && getSkillsList()
          .equals(other.getSkillsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasLv()) {
        hash = (37 * hash) + LV_FIELD_NUMBER;
        hash = (53 * hash) + getLv();
      }
      if (hasExperience()) {
        hash = (37 * hash) + EXPERIENCE_FIELD_NUMBER;
        hash = (53 * hash) + getExperience();
      }
      if (hasElementType()) {
        hash = (37 * hash) + ELEMENTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getElementType().hashCode();
      }
      if (hasPhysicalAttack()) {
        hash = (37 * hash) + PHYSICALATTACK_FIELD_NUMBER;
        hash = (53 * hash) + getPhysicalAttack();
      }
      if (hasPhysicalDefence()) {
        hash = (37 * hash) + PHYSICALDEFENCE_FIELD_NUMBER;
        hash = (53 * hash) + getPhysicalDefence();
      }
      if (hasMagicalAttack()) {
        hash = (37 * hash) + MAGICALATTACK_FIELD_NUMBER;
        hash = (53 * hash) + getMagicalAttack();
      }
      if (hasMagicalDefence()) {
        hash = (37 * hash) + MAGICALDEFENCE_FIELD_NUMBER;
        hash = (53 * hash) + getMagicalDefence();
      }
      if (hasAbsoluteAttack()) {
        hash = (37 * hash) + ABSOLUTEATTACK_FIELD_NUMBER;
        hash = (53 * hash) + getAbsoluteAttack();
      }
      if (hasSpeed()) {
        hash = (37 * hash) + SPEED_FIELD_NUMBER;
        hash = (53 * hash) + getSpeed();
      }
      if (hasMove()) {
        hash = (37 * hash) + MOVE_FIELD_NUMBER;
        hash = (53 * hash) + getMove();
      }
      if (hasAttackRange()) {
        hash = (37 * hash) + ATTACKRANGE_FIELD_NUMBER;
        hash = (53 * hash) + getAttackRange();
      }
      if (hasHp()) {
        hash = (37 * hash) + HP_FIELD_NUMBER;
        hash = (53 * hash) + getHp();
      }
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + getSkillsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.DatHeroData.DAT_HeroData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.DAT_HeroData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.DAT_HeroData)
        cn.wzj.netty.proto.DatHeroData.DAT_HeroDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.DatHeroData.internal_static_cn_wzj_netty_proto_DAT_HeroData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.DatHeroData.internal_static_cn_wzj_netty_proto_DAT_HeroData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.DatHeroData.DAT_HeroData.class, cn.wzj.netty.proto.DatHeroData.DAT_HeroData.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.DatHeroData.DAT_HeroData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getElementTypeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        experience_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (elementTypeBuilder_ == null) {
          elementType_ = null;
        } else {
          elementTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        physicalAttack_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        physicalDefence_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        magicalAttack_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        magicalDefence_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        absoluteAttack_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        move_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        attackRange_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        hp_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.DatHeroData.internal_static_cn_wzj_netty_proto_DAT_HeroData_descriptor;
      }

      public cn.wzj.netty.proto.DatHeroData.DAT_HeroData getDefaultInstanceForType() {
        return cn.wzj.netty.proto.DatHeroData.DAT_HeroData.getDefaultInstance();
      }

      public cn.wzj.netty.proto.DatHeroData.DAT_HeroData build() {
        cn.wzj.netty.proto.DatHeroData.DAT_HeroData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.DatHeroData.DAT_HeroData buildPartial() {
        cn.wzj.netty.proto.DatHeroData.DAT_HeroData result = new cn.wzj.netty.proto.DatHeroData.DAT_HeroData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lv_ = lv_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.experience_ = experience_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (elementTypeBuilder_ == null) {
          result.elementType_ = elementType_;
        } else {
          result.elementType_ = elementTypeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.physicalAttack_ = physicalAttack_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.physicalDefence_ = physicalDefence_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.magicalAttack_ = magicalAttack_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.magicalDefence_ = magicalDefence_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.absoluteAttack_ = absoluteAttack_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.move_ = move_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.attackRange_ = attackRange_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.hp_ = hp_;
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          skills_ = skills_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.skills_ = skills_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.DatHeroData.DAT_HeroData) {
          return mergeFrom((cn.wzj.netty.proto.DatHeroData.DAT_HeroData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.DatHeroData.DAT_HeroData other) {
        if (other == cn.wzj.netty.proto.DatHeroData.DAT_HeroData.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasLv()) {
          setLv(other.getLv());
        }
        if (other.hasExperience()) {
          setExperience(other.getExperience());
        }
        if (other.hasElementType()) {
          mergeElementType(other.getElementType());
        }
        if (other.hasPhysicalAttack()) {
          setPhysicalAttack(other.getPhysicalAttack());
        }
        if (other.hasPhysicalDefence()) {
          setPhysicalDefence(other.getPhysicalDefence());
        }
        if (other.hasMagicalAttack()) {
          setMagicalAttack(other.getMagicalAttack());
        }
        if (other.hasMagicalDefence()) {
          setMagicalDefence(other.getMagicalDefence());
        }
        if (other.hasAbsoluteAttack()) {
          setAbsoluteAttack(other.getAbsoluteAttack());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasMove()) {
          setMove(other.getMove());
        }
        if (other.hasAttackRange()) {
          setAttackRange(other.getAttackRange());
        }
        if (other.hasHp()) {
          setHp(other.getHp());
        }
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasLv()) {
          return false;
        }
        if (!hasExperience()) {
          return false;
        }
        if (!hasElementType()) {
          return false;
        }
        if (!hasPhysicalAttack()) {
          return false;
        }
        if (!hasPhysicalDefence()) {
          return false;
        }
        if (!hasMagicalAttack()) {
          return false;
        }
        if (!hasMagicalDefence()) {
          return false;
        }
        if (!hasAbsoluteAttack()) {
          return false;
        }
        if (!hasSpeed()) {
          return false;
        }
        if (!hasMove()) {
          return false;
        }
        if (!hasAttackRange()) {
          return false;
        }
        if (!hasHp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.DatHeroData.DAT_HeroData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.DatHeroData.DAT_HeroData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * Ψһid �������ݿ���¼
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * Ψһid �������ݿ���¼
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Ψһid �������ݿ���¼
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Ψһid �������ݿ���¼
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ψһid �������ݿ���¼
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ψһid �������ݿ���¼
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ӣ��id ���ڿͻ���ʶ��Ӣ����Դ
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      private int lv_ ;
      /**
       * <pre>
       * �ȼ�
       * </pre>
       *
       * <code>required int32 lv = 3;</code>
       */
      public boolean hasLv() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * �ȼ�
       * </pre>
       *
       * <code>required int32 lv = 3;</code>
       */
      public int getLv() {
        return lv_;
      }
      /**
       * <pre>
       * �ȼ�
       * </pre>
       *
       * <code>required int32 lv = 3;</code>
       */
      public Builder setLv(int value) {
        bitField0_ |= 0x00000004;
        lv_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �ȼ�
       * </pre>
       *
       * <code>required int32 lv = 3;</code>
       */
      public Builder clearLv() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lv_ = 0;
        onChanged();
        return this;
      }

      private int experience_ ;
      /**
       * <pre>
       * ����
       * </pre>
       *
       * <code>required int32 experience = 4;</code>
       */
      public boolean hasExperience() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * ����
       * </pre>
       *
       * <code>required int32 experience = 4;</code>
       */
      public int getExperience() {
        return experience_;
      }
      /**
       * <pre>
       * ����
       * </pre>
       *
       * <code>required int32 experience = 4;</code>
       */
      public Builder setExperience(int value) {
        bitField0_ |= 0x00000008;
        experience_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����
       * </pre>
       *
       * <code>required int32 experience = 4;</code>
       */
      public Builder clearExperience() {
        bitField0_ = (bitField0_ & ~0x00000008);
        experience_ = 0;
        onChanged();
        return this;
      }

      private cn.wzj.netty.proto.DatGeneral.DAT_ElementType elementType_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatGeneral.DAT_ElementType, cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder> elementTypeBuilder_;
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      public boolean hasElementType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementType getElementType() {
        if (elementTypeBuilder_ == null) {
          return elementType_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance() : elementType_;
        } else {
          return elementTypeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      public Builder setElementType(cn.wzj.netty.proto.DatGeneral.DAT_ElementType value) {
        if (elementTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          elementType_ = value;
          onChanged();
        } else {
          elementTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      public Builder setElementType(
          cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder builderForValue) {
        if (elementTypeBuilder_ == null) {
          elementType_ = builderForValue.build();
          onChanged();
        } else {
          elementTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      public Builder mergeElementType(cn.wzj.netty.proto.DatGeneral.DAT_ElementType value) {
        if (elementTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              elementType_ != null &&
              elementType_ != cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance()) {
            elementType_ =
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType.newBuilder(elementType_).mergeFrom(value).buildPartial();
          } else {
            elementType_ = value;
          }
          onChanged();
        } else {
          elementTypeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      public Builder clearElementType() {
        if (elementTypeBuilder_ == null) {
          elementType_ = null;
          onChanged();
        } else {
          elementTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder getElementTypeBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getElementTypeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder getElementTypeOrBuilder() {
        if (elementTypeBuilder_ != null) {
          return elementTypeBuilder_.getMessageOrBuilder();
        } else {
          return elementType_ == null ?
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance() : elementType_;
        }
      }
      /**
       * <pre>
       * Ԫ������
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatGeneral.DAT_ElementType, cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder> 
          getElementTypeFieldBuilder() {
        if (elementTypeBuilder_ == null) {
          elementTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType, cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder>(
                  getElementType(),
                  getParentForChildren(),
                  isClean());
          elementType_ = null;
        }
        return elementTypeBuilder_;
      }

      private int physicalAttack_ ;
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 physicalAttack = 6;</code>
       */
      public boolean hasPhysicalAttack() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 physicalAttack = 6;</code>
       */
      public int getPhysicalAttack() {
        return physicalAttack_;
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 physicalAttack = 6;</code>
       */
      public Builder setPhysicalAttack(int value) {
        bitField0_ |= 0x00000020;
        physicalAttack_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 physicalAttack = 6;</code>
       */
      public Builder clearPhysicalAttack() {
        bitField0_ = (bitField0_ & ~0x00000020);
        physicalAttack_ = 0;
        onChanged();
        return this;
      }

      private int physicalDefence_ ;
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 physicalDefence = 7;</code>
       */
      public boolean hasPhysicalDefence() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 physicalDefence = 7;</code>
       */
      public int getPhysicalDefence() {
        return physicalDefence_;
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 physicalDefence = 7;</code>
       */
      public Builder setPhysicalDefence(int value) {
        bitField0_ |= 0x00000040;
        physicalDefence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>required int32 physicalDefence = 7;</code>
       */
      public Builder clearPhysicalDefence() {
        bitField0_ = (bitField0_ & ~0x00000040);
        physicalDefence_ = 0;
        onChanged();
        return this;
      }

      private int magicalAttack_ ;
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magicalAttack = 8;</code>
       */
      public boolean hasMagicalAttack() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magicalAttack = 8;</code>
       */
      public int getMagicalAttack() {
        return magicalAttack_;
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magicalAttack = 8;</code>
       */
      public Builder setMagicalAttack(int value) {
        bitField0_ |= 0x00000080;
        magicalAttack_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magicalAttack = 8;</code>
       */
      public Builder clearMagicalAttack() {
        bitField0_ = (bitField0_ & ~0x00000080);
        magicalAttack_ = 0;
        onChanged();
        return this;
      }

      private int magicalDefence_ ;
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magicalDefence = 9;</code>
       */
      public boolean hasMagicalDefence() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magicalDefence = 9;</code>
       */
      public int getMagicalDefence() {
        return magicalDefence_;
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magicalDefence = 9;</code>
       */
      public Builder setMagicalDefence(int value) {
        bitField0_ |= 0x00000100;
        magicalDefence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ħ������
       * </pre>
       *
       * <code>required int32 magicalDefence = 9;</code>
       */
      public Builder clearMagicalDefence() {
        bitField0_ = (bitField0_ & ~0x00000100);
        magicalDefence_ = 0;
        onChanged();
        return this;
      }

      private int absoluteAttack_ ;
      /**
       * <pre>
       * ���Թ���
       * </pre>
       *
       * <code>required int32 absoluteAttack = 10;</code>
       */
      public boolean hasAbsoluteAttack() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       * ���Թ���
       * </pre>
       *
       * <code>required int32 absoluteAttack = 10;</code>
       */
      public int getAbsoluteAttack() {
        return absoluteAttack_;
      }
      /**
       * <pre>
       * ���Թ���
       * </pre>
       *
       * <code>required int32 absoluteAttack = 10;</code>
       */
      public Builder setAbsoluteAttack(int value) {
        bitField0_ |= 0x00000200;
        absoluteAttack_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ���Թ���
       * </pre>
       *
       * <code>required int32 absoluteAttack = 10;</code>
       */
      public Builder clearAbsoluteAttack() {
        bitField0_ = (bitField0_ & ~0x00000200);
        absoluteAttack_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <pre>
       * �ж��ٶ�
       * </pre>
       *
       * <code>required int32 speed = 11;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <pre>
       * �ж��ٶ�
       * </pre>
       *
       * <code>required int32 speed = 11;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <pre>
       * �ж��ٶ�
       * </pre>
       *
       * <code>required int32 speed = 11;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000400;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �ж��ٶ�
       * </pre>
       *
       * <code>required int32 speed = 11;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000400);
        speed_ = 0;
        onChanged();
        return this;
      }

      private int move_ ;
      /**
       * <pre>
       * �ƶ�������
       * </pre>
       *
       * <code>required int32 move = 12;</code>
       */
      public boolean hasMove() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <pre>
       * �ƶ�������
       * </pre>
       *
       * <code>required int32 move = 12;</code>
       */
      public int getMove() {
        return move_;
      }
      /**
       * <pre>
       * �ƶ�������
       * </pre>
       *
       * <code>required int32 move = 12;</code>
       */
      public Builder setMove(int value) {
        bitField0_ |= 0x00000800;
        move_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �ƶ�������
       * </pre>
       *
       * <code>required int32 move = 12;</code>
       */
      public Builder clearMove() {
        bitField0_ = (bitField0_ & ~0x00000800);
        move_ = 0;
        onChanged();
        return this;
      }

      private int attackRange_ ;
      /**
       * <pre>
       *������Χ
       * </pre>
       *
       * <code>required int32 attackRange = 13;</code>
       */
      public boolean hasAttackRange() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <pre>
       *������Χ
       * </pre>
       *
       * <code>required int32 attackRange = 13;</code>
       */
      public int getAttackRange() {
        return attackRange_;
      }
      /**
       * <pre>
       *������Χ
       * </pre>
       *
       * <code>required int32 attackRange = 13;</code>
       */
      public Builder setAttackRange(int value) {
        bitField0_ |= 0x00001000;
        attackRange_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������Χ
       * </pre>
       *
       * <code>required int32 attackRange = 13;</code>
       */
      public Builder clearAttackRange() {
        bitField0_ = (bitField0_ & ~0x00001000);
        attackRange_ = 0;
        onChanged();
        return this;
      }

      private int hp_ ;
      /**
       * <pre>
       * ����ֵ
       * </pre>
       *
       * <code>required int32 hp = 14;</code>
       */
      public boolean hasHp() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <pre>
       * ����ֵ
       * </pre>
       *
       * <code>required int32 hp = 14;</code>
       */
      public int getHp() {
        return hp_;
      }
      /**
       * <pre>
       * ����ֵ
       * </pre>
       *
       * <code>required int32 hp = 14;</code>
       */
      public Builder setHp(int value) {
        bitField0_ |= 0x00002000;
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����ֵ
       * </pre>
       *
       * <code>required int32 hp = 14;</code>
       */
      public Builder clearHp() {
        bitField0_ = (bitField0_ & ~0x00002000);
        hp_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00004000) == 0x00004000)) {
          skills_ = new com.google.protobuf.LazyStringArrayList(skills_);
          bitField0_ |= 0x00004000;
         }
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSkillsList() {
        return skills_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public int getSkillsCount() {
        return skills_.size();
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public java.lang.String getSkills(int index) {
        return skills_.get(index);
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public com.google.protobuf.ByteString
          getSkillsBytes(int index) {
        return skills_.getByteString(index);
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public Builder setSkills(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public Builder addSkills(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public Builder addAllSkills(
          java.lang.Iterable<java.lang.String> values) {
        ensureSkillsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skills_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public Builder clearSkills() {
        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ӣ�۵ļ����б�
       * </pre>
       *
       * <code>repeated string skills = 15;</code>
       */
      public Builder addSkillsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.DAT_HeroData)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.DAT_HeroData)
    private static final cn.wzj.netty.proto.DatHeroData.DAT_HeroData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.DatHeroData.DAT_HeroData();
    }

    public static cn.wzj.netty.proto.DatHeroData.DAT_HeroData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DAT_HeroData>
        PARSER = new com.google.protobuf.AbstractParser<DAT_HeroData>() {
      public DAT_HeroData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DAT_HeroData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DAT_HeroData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DAT_HeroData> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.DatHeroData.DAT_HeroData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_DAT_HeroData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_DAT_HeroData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Dat_HeroData.proto\022\022cn.wzj.netty.proto" +
      "\032\021Dat_General.proto\"\307\002\n\014DAT_HeroData\022\013\n\003" +
      "uid\030\001 \002(\t\022\n\n\002id\030\002 \002(\t\022\n\n\002lv\030\003 \002(\005\022\022\n\nexp" +
      "erience\030\004 \002(\005\0228\n\013elementType\030\005 \002(\0132#.cn." +
      "wzj.netty.proto.DAT_ElementType\022\026\n\016physi" +
      "calAttack\030\006 \002(\005\022\027\n\017physicalDefence\030\007 \002(\005" +
      "\022\025\n\rmagicalAttack\030\010 \002(\005\022\026\n\016magicalDefenc" +
      "e\030\t \002(\005\022\026\n\016absoluteAttack\030\n \002(\005\022\r\n\005speed" +
      "\030\013 \002(\005\022\014\n\004move\030\014 \002(\005\022\023\n\013attackRange\030\r \002(" +
      "\005\022\n\n\002hp\030\016 \002(\005\022\016\n\006skills\030\017 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.wzj.netty.proto.DatGeneral.getDescriptor(),
        }, assigner);
    internal_static_cn_wzj_netty_proto_DAT_HeroData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_wzj_netty_proto_DAT_HeroData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_DAT_HeroData_descriptor,
        new java.lang.String[] { "Uid", "Id", "Lv", "Experience", "ElementType", "PhysicalAttack", "PhysicalDefence", "MagicalAttack", "MagicalDefence", "AbsoluteAttack", "Speed", "Move", "AttackRange", "Hp", "Skills", });
    cn.wzj.netty.proto.DatGeneral.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
