// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_NewHero.proto

package cn.wzj.netty.proto;

public final class MsgNewHero {
  private MsgNewHero() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_NewHeroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.C2S_NewHero)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
     */
    boolean hasElementType();
    /**
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
     */
    cn.wzj.netty.proto.DatGeneral.DAT_ElementType getElementType();
    /**
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
     */
    cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder getElementTypeOrBuilder();
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.C2S_NewHero}
   */
  public  static final class C2S_NewHero extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.C2S_NewHero)
      C2S_NewHeroOrBuilder {
    // Use C2S_NewHero.newBuilder() to construct.
    private C2S_NewHero(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_NewHero() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_NewHero(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = elementType_.toBuilder();
              }
              elementType_ = input.readMessage(cn.wzj.netty.proto.DatGeneral.DAT_ElementType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(elementType_);
                elementType_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_C2S_NewHero_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_C2S_NewHero_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.MsgNewHero.C2S_NewHero.class, cn.wzj.netty.proto.MsgNewHero.C2S_NewHero.Builder.class);
    }

    private int bitField0_;
    public static final int ELEMENTTYPE_FIELD_NUMBER = 1;
    private cn.wzj.netty.proto.DatGeneral.DAT_ElementType elementType_;
    /**
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
     */
    public boolean hasElementType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
     */
    public cn.wzj.netty.proto.DatGeneral.DAT_ElementType getElementType() {
      return elementType_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance() : elementType_;
    }
    /**
     * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
     */
    public cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder getElementTypeOrBuilder() {
      return elementType_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance() : elementType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasElementType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getElementType());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getElementType());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.MsgNewHero.C2S_NewHero)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.MsgNewHero.C2S_NewHero other = (cn.wzj.netty.proto.MsgNewHero.C2S_NewHero) obj;

      boolean result = true;
      result = result && (hasElementType() == other.hasElementType());
      if (hasElementType()) {
        result = result && getElementType()
            .equals(other.getElementType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasElementType()) {
        hash = (37 * hash) + ELEMENTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getElementType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.MsgNewHero.C2S_NewHero prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.C2S_NewHero}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.C2S_NewHero)
        cn.wzj.netty.proto.MsgNewHero.C2S_NewHeroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_C2S_NewHero_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_C2S_NewHero_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.MsgNewHero.C2S_NewHero.class, cn.wzj.netty.proto.MsgNewHero.C2S_NewHero.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.MsgNewHero.C2S_NewHero.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getElementTypeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (elementTypeBuilder_ == null) {
          elementType_ = null;
        } else {
          elementTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_C2S_NewHero_descriptor;
      }

      public cn.wzj.netty.proto.MsgNewHero.C2S_NewHero getDefaultInstanceForType() {
        return cn.wzj.netty.proto.MsgNewHero.C2S_NewHero.getDefaultInstance();
      }

      public cn.wzj.netty.proto.MsgNewHero.C2S_NewHero build() {
        cn.wzj.netty.proto.MsgNewHero.C2S_NewHero result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.MsgNewHero.C2S_NewHero buildPartial() {
        cn.wzj.netty.proto.MsgNewHero.C2S_NewHero result = new cn.wzj.netty.proto.MsgNewHero.C2S_NewHero(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (elementTypeBuilder_ == null) {
          result.elementType_ = elementType_;
        } else {
          result.elementType_ = elementTypeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.MsgNewHero.C2S_NewHero) {
          return mergeFrom((cn.wzj.netty.proto.MsgNewHero.C2S_NewHero)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.MsgNewHero.C2S_NewHero other) {
        if (other == cn.wzj.netty.proto.MsgNewHero.C2S_NewHero.getDefaultInstance()) return this;
        if (other.hasElementType()) {
          mergeElementType(other.getElementType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasElementType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.MsgNewHero.C2S_NewHero parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.MsgNewHero.C2S_NewHero) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private cn.wzj.netty.proto.DatGeneral.DAT_ElementType elementType_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatGeneral.DAT_ElementType, cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder> elementTypeBuilder_;
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      public boolean hasElementType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementType getElementType() {
        if (elementTypeBuilder_ == null) {
          return elementType_ == null ? cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance() : elementType_;
        } else {
          return elementTypeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      public Builder setElementType(cn.wzj.netty.proto.DatGeneral.DAT_ElementType value) {
        if (elementTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          elementType_ = value;
          onChanged();
        } else {
          elementTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      public Builder setElementType(
          cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder builderForValue) {
        if (elementTypeBuilder_ == null) {
          elementType_ = builderForValue.build();
          onChanged();
        } else {
          elementTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      public Builder mergeElementType(cn.wzj.netty.proto.DatGeneral.DAT_ElementType value) {
        if (elementTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              elementType_ != null &&
              elementType_ != cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance()) {
            elementType_ =
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType.newBuilder(elementType_).mergeFrom(value).buildPartial();
          } else {
            elementType_ = value;
          }
          onChanged();
        } else {
          elementTypeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      public Builder clearElementType() {
        if (elementTypeBuilder_ == null) {
          elementType_ = null;
          onChanged();
        } else {
          elementTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder getElementTypeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getElementTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      public cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder getElementTypeOrBuilder() {
        if (elementTypeBuilder_ != null) {
          return elementTypeBuilder_.getMessageOrBuilder();
        } else {
          return elementType_ == null ?
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType.getDefaultInstance() : elementType_;
        }
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_ElementType elementType = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatGeneral.DAT_ElementType, cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder> 
          getElementTypeFieldBuilder() {
        if (elementTypeBuilder_ == null) {
          elementTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.wzj.netty.proto.DatGeneral.DAT_ElementType, cn.wzj.netty.proto.DatGeneral.DAT_ElementType.Builder, cn.wzj.netty.proto.DatGeneral.DAT_ElementTypeOrBuilder>(
                  getElementType(),
                  getParentForChildren(),
                  isClean());
          elementType_ = null;
        }
        return elementTypeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.C2S_NewHero)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.C2S_NewHero)
    private static final cn.wzj.netty.proto.MsgNewHero.C2S_NewHero DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.MsgNewHero.C2S_NewHero();
    }

    public static cn.wzj.netty.proto.MsgNewHero.C2S_NewHero getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_NewHero>
        PARSER = new com.google.protobuf.AbstractParser<C2S_NewHero>() {
      public C2S_NewHero parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S_NewHero(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_NewHero> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_NewHero> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.MsgNewHero.C2S_NewHero getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_NewHeroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.S2C_NewHero)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 ret = 1;</code>
     */
    boolean hasRet();
    /**
     * <code>required int32 ret = 1;</code>
     */
    int getRet();

    /**
     * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
     */
    boolean hasHero();
    /**
     * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
     */
    cn.wzj.netty.proto.DatHeroData.DAT_HeroData getHero();
    /**
     * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
     */
    cn.wzj.netty.proto.DatHeroData.DAT_HeroDataOrBuilder getHeroOrBuilder();
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.S2C_NewHero}
   */
  public  static final class S2C_NewHero extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.S2C_NewHero)
      S2C_NewHeroOrBuilder {
    // Use S2C_NewHero.newBuilder() to construct.
    private S2C_NewHero(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_NewHero() {
      ret_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_NewHero(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readInt32();
              break;
            }
            case 18: {
              cn.wzj.netty.proto.DatHeroData.DAT_HeroData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = hero_.toBuilder();
              }
              hero_ = input.readMessage(cn.wzj.netty.proto.DatHeroData.DAT_HeroData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hero_);
                hero_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_S2C_NewHero_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_S2C_NewHero_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.MsgNewHero.S2C_NewHero.class, cn.wzj.netty.proto.MsgNewHero.S2C_NewHero.Builder.class);
    }

    private int bitField0_;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>required int32 ret = 1;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }

    public static final int HERO_FIELD_NUMBER = 2;
    private cn.wzj.netty.proto.DatHeroData.DAT_HeroData hero_;
    /**
     * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
     */
    public boolean hasHero() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
     */
    public cn.wzj.netty.proto.DatHeroData.DAT_HeroData getHero() {
      return hero_ == null ? cn.wzj.netty.proto.DatHeroData.DAT_HeroData.getDefaultInstance() : hero_;
    }
    /**
     * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
     */
    public cn.wzj.netty.proto.DatHeroData.DAT_HeroDataOrBuilder getHeroOrBuilder() {
      return hero_ == null ? cn.wzj.netty.proto.DatHeroData.DAT_HeroData.getDefaultInstance() : hero_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHero()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHero().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getHero());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHero());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.MsgNewHero.S2C_NewHero)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.MsgNewHero.S2C_NewHero other = (cn.wzj.netty.proto.MsgNewHero.S2C_NewHero) obj;

      boolean result = true;
      result = result && (hasRet() == other.hasRet());
      if (hasRet()) {
        result = result && (getRet()
            == other.getRet());
      }
      result = result && (hasHero() == other.hasHero());
      if (hasHero()) {
        result = result && getHero()
            .equals(other.getHero());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRet()) {
        hash = (37 * hash) + RET_FIELD_NUMBER;
        hash = (53 * hash) + getRet();
      }
      if (hasHero()) {
        hash = (37 * hash) + HERO_FIELD_NUMBER;
        hash = (53 * hash) + getHero().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.MsgNewHero.S2C_NewHero prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.S2C_NewHero}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.S2C_NewHero)
        cn.wzj.netty.proto.MsgNewHero.S2C_NewHeroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_S2C_NewHero_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_S2C_NewHero_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.MsgNewHero.S2C_NewHero.class, cn.wzj.netty.proto.MsgNewHero.S2C_NewHero.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.MsgNewHero.S2C_NewHero.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeroFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (heroBuilder_ == null) {
          hero_ = null;
        } else {
          heroBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.MsgNewHero.internal_static_cn_wzj_netty_proto_S2C_NewHero_descriptor;
      }

      public cn.wzj.netty.proto.MsgNewHero.S2C_NewHero getDefaultInstanceForType() {
        return cn.wzj.netty.proto.MsgNewHero.S2C_NewHero.getDefaultInstance();
      }

      public cn.wzj.netty.proto.MsgNewHero.S2C_NewHero build() {
        cn.wzj.netty.proto.MsgNewHero.S2C_NewHero result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.MsgNewHero.S2C_NewHero buildPartial() {
        cn.wzj.netty.proto.MsgNewHero.S2C_NewHero result = new cn.wzj.netty.proto.MsgNewHero.S2C_NewHero(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (heroBuilder_ == null) {
          result.hero_ = hero_;
        } else {
          result.hero_ = heroBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.MsgNewHero.S2C_NewHero) {
          return mergeFrom((cn.wzj.netty.proto.MsgNewHero.S2C_NewHero)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.MsgNewHero.S2C_NewHero other) {
        if (other == cn.wzj.netty.proto.MsgNewHero.S2C_NewHero.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasHero()) {
          mergeHero(other.getHero());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          return false;
        }
        if (!hasHero()) {
          return false;
        }
        if (!getHero().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.MsgNewHero.S2C_NewHero parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.MsgNewHero.S2C_NewHero) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ret_ ;
      /**
       * <code>required int32 ret = 1;</code>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      private cn.wzj.netty.proto.DatHeroData.DAT_HeroData hero_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatHeroData.DAT_HeroData, cn.wzj.netty.proto.DatHeroData.DAT_HeroData.Builder, cn.wzj.netty.proto.DatHeroData.DAT_HeroDataOrBuilder> heroBuilder_;
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      public boolean hasHero() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      public cn.wzj.netty.proto.DatHeroData.DAT_HeroData getHero() {
        if (heroBuilder_ == null) {
          return hero_ == null ? cn.wzj.netty.proto.DatHeroData.DAT_HeroData.getDefaultInstance() : hero_;
        } else {
          return heroBuilder_.getMessage();
        }
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      public Builder setHero(cn.wzj.netty.proto.DatHeroData.DAT_HeroData value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hero_ = value;
          onChanged();
        } else {
          heroBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      public Builder setHero(
          cn.wzj.netty.proto.DatHeroData.DAT_HeroData.Builder builderForValue) {
        if (heroBuilder_ == null) {
          hero_ = builderForValue.build();
          onChanged();
        } else {
          heroBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      public Builder mergeHero(cn.wzj.netty.proto.DatHeroData.DAT_HeroData value) {
        if (heroBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              hero_ != null &&
              hero_ != cn.wzj.netty.proto.DatHeroData.DAT_HeroData.getDefaultInstance()) {
            hero_ =
              cn.wzj.netty.proto.DatHeroData.DAT_HeroData.newBuilder(hero_).mergeFrom(value).buildPartial();
          } else {
            hero_ = value;
          }
          onChanged();
        } else {
          heroBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      public Builder clearHero() {
        if (heroBuilder_ == null) {
          hero_ = null;
          onChanged();
        } else {
          heroBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      public cn.wzj.netty.proto.DatHeroData.DAT_HeroData.Builder getHeroBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHeroFieldBuilder().getBuilder();
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      public cn.wzj.netty.proto.DatHeroData.DAT_HeroDataOrBuilder getHeroOrBuilder() {
        if (heroBuilder_ != null) {
          return heroBuilder_.getMessageOrBuilder();
        } else {
          return hero_ == null ?
              cn.wzj.netty.proto.DatHeroData.DAT_HeroData.getDefaultInstance() : hero_;
        }
      }
      /**
       * <code>required .cn.wzj.netty.proto.DAT_HeroData hero = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatHeroData.DAT_HeroData, cn.wzj.netty.proto.DatHeroData.DAT_HeroData.Builder, cn.wzj.netty.proto.DatHeroData.DAT_HeroDataOrBuilder> 
          getHeroFieldBuilder() {
        if (heroBuilder_ == null) {
          heroBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.wzj.netty.proto.DatHeroData.DAT_HeroData, cn.wzj.netty.proto.DatHeroData.DAT_HeroData.Builder, cn.wzj.netty.proto.DatHeroData.DAT_HeroDataOrBuilder>(
                  getHero(),
                  getParentForChildren(),
                  isClean());
          hero_ = null;
        }
        return heroBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.S2C_NewHero)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.S2C_NewHero)
    private static final cn.wzj.netty.proto.MsgNewHero.S2C_NewHero DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.MsgNewHero.S2C_NewHero();
    }

    public static cn.wzj.netty.proto.MsgNewHero.S2C_NewHero getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_NewHero>
        PARSER = new com.google.protobuf.AbstractParser<S2C_NewHero>() {
      public S2C_NewHero parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new S2C_NewHero(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_NewHero> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_NewHero> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.MsgNewHero.S2C_NewHero getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_C2S_NewHero_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_C2S_NewHero_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_S2C_NewHero_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_S2C_NewHero_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Msg_NewHero.proto\022\022cn.wzj.netty.proto\032" +
      "\021Dat_General.proto\032\022Dat_HeroData.proto\"G" +
      "\n\013C2S_NewHero\0228\n\013elementType\030\001 \002(\0132#.cn." +
      "wzj.netty.proto.DAT_ElementType\"J\n\013S2C_N" +
      "ewHero\022\013\n\003ret\030\001 \002(\005\022.\n\004hero\030\002 \002(\0132 .cn.w" +
      "zj.netty.proto.DAT_HeroData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.wzj.netty.proto.DatGeneral.getDescriptor(),
          cn.wzj.netty.proto.DatHeroData.getDescriptor(),
        }, assigner);
    internal_static_cn_wzj_netty_proto_C2S_NewHero_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_wzj_netty_proto_C2S_NewHero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_C2S_NewHero_descriptor,
        new java.lang.String[] { "ElementType", });
    internal_static_cn_wzj_netty_proto_S2C_NewHero_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_wzj_netty_proto_S2C_NewHero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_S2C_NewHero_descriptor,
        new java.lang.String[] { "Ret", "Hero", });
    cn.wzj.netty.proto.DatGeneral.getDescriptor();
    cn.wzj.netty.proto.DatHeroData.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
