// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_RoleInit.proto

package cn.wzj.netty.proto;

public final class MsgRoleInit {
  private MsgRoleInit() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_RoleInitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.C2S_RoleInit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>required string roleID = 1;</code>
     */
    boolean hasRoleID();
    /**
     * <pre>
     * </pre>
     *
     * <code>required string roleID = 1;</code>
     */
    java.lang.String getRoleID();
    /**
     * <pre>
     * </pre>
     *
     * <code>required string roleID = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoleIDBytes();
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.C2S_RoleInit}
   */
  public  static final class C2S_RoleInit extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.C2S_RoleInit)
      C2S_RoleInitOrBuilder {
    // Use C2S_RoleInit.newBuilder() to construct.
    private C2S_RoleInit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_RoleInit() {
      roleID_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_RoleInit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              roleID_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_C2S_RoleInit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_C2S_RoleInit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit.class, cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit.Builder.class);
    }

    private int bitField0_;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object roleID_;
    /**
     * <pre>
     * </pre>
     *
     * <code>required string roleID = 1;</code>
     */
    public boolean hasRoleID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>required string roleID = 1;</code>
     */
    public java.lang.String getRoleID() {
      java.lang.Object ref = roleID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          roleID_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>required string roleID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoleIDBytes() {
      java.lang.Object ref = roleID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRoleID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roleID_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roleID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit other = (cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit) obj;

      boolean result = true;
      result = result && (hasRoleID() == other.hasRoleID());
      if (hasRoleID()) {
        result = result && getRoleID()
            .equals(other.getRoleID());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRoleID()) {
        hash = (37 * hash) + ROLEID_FIELD_NUMBER;
        hash = (53 * hash) + getRoleID().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.C2S_RoleInit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.C2S_RoleInit)
        cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_C2S_RoleInit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_C2S_RoleInit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit.class, cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        roleID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_C2S_RoleInit_descriptor;
      }

      public cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit getDefaultInstanceForType() {
        return cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit.getDefaultInstance();
      }

      public cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit build() {
        cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit buildPartial() {
        cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit result = new cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roleID_ = roleID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit) {
          return mergeFrom((cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit other) {
        if (other == cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit.getDefaultInstance()) return this;
        if (other.hasRoleID()) {
          bitField0_ |= 0x00000001;
          roleID_ = other.roleID_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoleID()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object roleID_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>required string roleID = 1;</code>
       */
      public boolean hasRoleID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string roleID = 1;</code>
       */
      public java.lang.String getRoleID() {
        java.lang.Object ref = roleID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            roleID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string roleID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoleIDBytes() {
        java.lang.Object ref = roleID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roleID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string roleID = 1;</code>
       */
      public Builder setRoleID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roleID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string roleID = 1;</code>
       */
      public Builder clearRoleID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roleID_ = getDefaultInstance().getRoleID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string roleID = 1;</code>
       */
      public Builder setRoleIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roleID_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.C2S_RoleInit)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.C2S_RoleInit)
    private static final cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit();
    }

    public static cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_RoleInit>
        PARSER = new com.google.protobuf.AbstractParser<C2S_RoleInit>() {
      public C2S_RoleInit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S_RoleInit(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_RoleInit> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_RoleInit> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.MsgRoleInit.C2S_RoleInit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_RoleInitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.S2C_RoleInit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>required int32 ret = 1;</code>
     */
    boolean hasRet();
    /**
     * <pre>
     * </pre>
     *
     * <code>required int32 ret = 1;</code>
     */
    int getRet();

    /**
     * <pre>
     *��ʼ��������Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
     */
    boolean hasUserData();
    /**
     * <pre>
     *��ʼ��������Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
     */
    cn.wzj.netty.proto.DatUserData.DAT_UserData getUserData();
    /**
     * <pre>
     *��ʼ��������Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
     */
    cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder getUserDataOrBuilder();
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.S2C_RoleInit}
   */
  public  static final class S2C_RoleInit extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.S2C_RoleInit)
      S2C_RoleInitOrBuilder {
    // Use S2C_RoleInit.newBuilder() to construct.
    private S2C_RoleInit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_RoleInit() {
      ret_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_RoleInit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readInt32();
              break;
            }
            case 18: {
              cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = userData_.toBuilder();
              }
              userData_ = input.readMessage(cn.wzj.netty.proto.DatUserData.DAT_UserData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userData_);
                userData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_S2C_RoleInit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_S2C_RoleInit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit.class, cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit.Builder.class);
    }

    private int bitField0_;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <pre>
     * </pre>
     *
     * <code>required int32 ret = 1;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>required int32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }

    public static final int USERDATA_FIELD_NUMBER = 2;
    private cn.wzj.netty.proto.DatUserData.DAT_UserData userData_;
    /**
     * <pre>
     *��ʼ��������Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
     */
    public boolean hasUserData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *��ʼ��������Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
     */
    public cn.wzj.netty.proto.DatUserData.DAT_UserData getUserData() {
      return userData_ == null ? cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance() : userData_;
    }
    /**
     * <pre>
     *��ʼ��������Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
     */
    public cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder getUserDataOrBuilder() {
      return userData_ == null ? cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance() : userData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUserData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getUserData());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUserData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit other = (cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit) obj;

      boolean result = true;
      result = result && (hasRet() == other.hasRet());
      if (hasRet()) {
        result = result && (getRet()
            == other.getRet());
      }
      result = result && (hasUserData() == other.hasUserData());
      if (hasUserData()) {
        result = result && getUserData()
            .equals(other.getUserData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRet()) {
        hash = (37 * hash) + RET_FIELD_NUMBER;
        hash = (53 * hash) + getRet();
      }
      if (hasUserData()) {
        hash = (37 * hash) + USERDATA_FIELD_NUMBER;
        hash = (53 * hash) + getUserData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.S2C_RoleInit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.S2C_RoleInit)
        cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_S2C_RoleInit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_S2C_RoleInit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit.class, cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (userDataBuilder_ == null) {
          userData_ = null;
        } else {
          userDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.MsgRoleInit.internal_static_cn_wzj_netty_proto_S2C_RoleInit_descriptor;
      }

      public cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit getDefaultInstanceForType() {
        return cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit.getDefaultInstance();
      }

      public cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit build() {
        cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit buildPartial() {
        cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit result = new cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (userDataBuilder_ == null) {
          result.userData_ = userData_;
        } else {
          result.userData_ = userDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit) {
          return mergeFrom((cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit other) {
        if (other == cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasUserData()) {
          mergeUserData(other.getUserData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          return false;
        }
        if (!hasUserData()) {
          return false;
        }
        if (!getUserData().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ret_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>required int32 ret = 1;</code>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required int32 ret = 1;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required int32 ret = 1;</code>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required int32 ret = 1;</code>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      private cn.wzj.netty.proto.DatUserData.DAT_UserData userData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatUserData.DAT_UserData, cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder, cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder> userDataBuilder_;
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      public boolean hasUserData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      public cn.wzj.netty.proto.DatUserData.DAT_UserData getUserData() {
        if (userDataBuilder_ == null) {
          return userData_ == null ? cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance() : userData_;
        } else {
          return userDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      public Builder setUserData(cn.wzj.netty.proto.DatUserData.DAT_UserData value) {
        if (userDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userData_ = value;
          onChanged();
        } else {
          userDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      public Builder setUserData(
          cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder builderForValue) {
        if (userDataBuilder_ == null) {
          userData_ = builderForValue.build();
          onChanged();
        } else {
          userDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      public Builder mergeUserData(cn.wzj.netty.proto.DatUserData.DAT_UserData value) {
        if (userDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              userData_ != null &&
              userData_ != cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance()) {
            userData_ =
              cn.wzj.netty.proto.DatUserData.DAT_UserData.newBuilder(userData_).mergeFrom(value).buildPartial();
          } else {
            userData_ = value;
          }
          onChanged();
        } else {
          userDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      public Builder clearUserData() {
        if (userDataBuilder_ == null) {
          userData_ = null;
          onChanged();
        } else {
          userDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      public cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder getUserDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUserDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      public cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder getUserDataOrBuilder() {
        if (userDataBuilder_ != null) {
          return userDataBuilder_.getMessageOrBuilder();
        } else {
          return userData_ == null ?
              cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance() : userData_;
        }
      }
      /**
       * <pre>
       *��ʼ��������Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatUserData.DAT_UserData, cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder, cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder> 
          getUserDataFieldBuilder() {
        if (userDataBuilder_ == null) {
          userDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.wzj.netty.proto.DatUserData.DAT_UserData, cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder, cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder>(
                  getUserData(),
                  getParentForChildren(),
                  isClean());
          userData_ = null;
        }
        return userDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.S2C_RoleInit)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.S2C_RoleInit)
    private static final cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit();
    }

    public static cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_RoleInit>
        PARSER = new com.google.protobuf.AbstractParser<S2C_RoleInit>() {
      public S2C_RoleInit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new S2C_RoleInit(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_RoleInit> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_RoleInit> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.MsgRoleInit.S2C_RoleInit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_C2S_RoleInit_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_C2S_RoleInit_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_S2C_RoleInit_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_S2C_RoleInit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Msg_RoleInit.proto\022\022cn.wzj.netty.proto" +
      "\032\022Dat_UserData.proto\"\036\n\014C2S_RoleInit\022\016\n\006" +
      "roleID\030\001 \002(\t\"O\n\014S2C_RoleInit\022\013\n\003ret\030\001 \002(" +
      "\005\0222\n\010userData\030\002 \002(\0132 .cn.wzj.netty.proto" +
      ".DAT_UserData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.wzj.netty.proto.DatUserData.getDescriptor(),
        }, assigner);
    internal_static_cn_wzj_netty_proto_C2S_RoleInit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_wzj_netty_proto_C2S_RoleInit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_C2S_RoleInit_descriptor,
        new java.lang.String[] { "RoleID", });
    internal_static_cn_wzj_netty_proto_S2C_RoleInit_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_wzj_netty_proto_S2C_RoleInit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_S2C_RoleInit_descriptor,
        new java.lang.String[] { "Ret", "UserData", });
    cn.wzj.netty.proto.DatUserData.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
