// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_UserData.proto

package cn.wzj.netty.proto;

public final class MsgUserData {
  private MsgUserData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_UserDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.C2S_UserData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * �û�uid
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <pre>
     * �û�uid
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <pre>
     * �û�uid
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     * ����У��������
     * </pre>
     *
     * <code>required string code = 2;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     * ����У��������
     * </pre>
     *
     * <code>required string code = 2;</code>
     */
    java.lang.String getCode();
    /**
     * <pre>
     * ����У��������
     * </pre>
     *
     * <code>required string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.C2S_UserData}
   */
  public  static final class C2S_UserData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.C2S_UserData)
      C2S_UserDataOrBuilder {
    // Use C2S_UserData.newBuilder() to construct.
    private C2S_UserData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_UserData() {
      uid_ = "";
      code_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_UserData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              code_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_C2S_UserData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_C2S_UserData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.MsgUserData.C2S_UserData.class, cn.wzj.netty.proto.MsgUserData.C2S_UserData.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * �û�uid
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * �û�uid
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * �û�uid
     * </pre>
     *
     * <code>required string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <pre>
     * ����У��������
     * </pre>
     *
     * <code>required string code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * ����У��������
     * </pre>
     *
     * <code>required string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * ����У��������
     * </pre>
     *
     * <code>required string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.MsgUserData.C2S_UserData)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.MsgUserData.C2S_UserData other = (cn.wzj.netty.proto.MsgUserData.C2S_UserData) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && getUid()
            .equals(other.getUid());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && getCode()
            .equals(other.getCode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.MsgUserData.C2S_UserData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.C2S_UserData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.C2S_UserData)
        cn.wzj.netty.proto.MsgUserData.C2S_UserDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_C2S_UserData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_C2S_UserData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.MsgUserData.C2S_UserData.class, cn.wzj.netty.proto.MsgUserData.C2S_UserData.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.MsgUserData.C2S_UserData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_C2S_UserData_descriptor;
      }

      public cn.wzj.netty.proto.MsgUserData.C2S_UserData getDefaultInstanceForType() {
        return cn.wzj.netty.proto.MsgUserData.C2S_UserData.getDefaultInstance();
      }

      public cn.wzj.netty.proto.MsgUserData.C2S_UserData build() {
        cn.wzj.netty.proto.MsgUserData.C2S_UserData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.MsgUserData.C2S_UserData buildPartial() {
        cn.wzj.netty.proto.MsgUserData.C2S_UserData result = new cn.wzj.netty.proto.MsgUserData.C2S_UserData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.MsgUserData.C2S_UserData) {
          return mergeFrom((cn.wzj.netty.proto.MsgUserData.C2S_UserData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.MsgUserData.C2S_UserData other) {
        if (other == cn.wzj.netty.proto.MsgUserData.C2S_UserData.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000002;
          code_ = other.code_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.MsgUserData.C2S_UserData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.MsgUserData.C2S_UserData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * �û�uid
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * �û�uid
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * �û�uid
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * �û�uid
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �û�uid
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �û�uid
       * </pre>
       *
       * <code>required string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <pre>
       * ����У��������
       * </pre>
       *
       * <code>required string code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * ����У��������
       * </pre>
       *
       * <code>required string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ����У��������
       * </pre>
       *
       * <code>required string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ����У��������
       * </pre>
       *
       * <code>required string code = 2;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����У��������
       * </pre>
       *
       * <code>required string code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ����У��������
       * </pre>
       *
       * <code>required string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.C2S_UserData)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.C2S_UserData)
    private static final cn.wzj.netty.proto.MsgUserData.C2S_UserData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.MsgUserData.C2S_UserData();
    }

    public static cn.wzj.netty.proto.MsgUserData.C2S_UserData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_UserData>
        PARSER = new com.google.protobuf.AbstractParser<C2S_UserData>() {
      public C2S_UserData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S_UserData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_UserData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_UserData> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.MsgUserData.C2S_UserData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_UserDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.wzj.netty.proto.S2C_UserData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 ret = 1;</code>
     */
    boolean hasRet();
    /**
     * <code>required int32 ret = 1;</code>
     */
    int getRet();

    /**
     * <pre>
     * �Ƿ����û�
     * </pre>
     *
     * <code>required bool newUser = 2;</code>
     */
    boolean hasNewUser();
    /**
     * <pre>
     * �Ƿ����û�
     * </pre>
     *
     * <code>required bool newUser = 2;</code>
     */
    boolean getNewUser();

    /**
     * <pre>
     *���ҵ���Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
     */
    boolean hasUserData();
    /**
     * <pre>
     *���ҵ���Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
     */
    cn.wzj.netty.proto.DatUserData.DAT_UserData getUserData();
    /**
     * <pre>
     *���ҵ���Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
     */
    cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder getUserDataOrBuilder();
  }
  /**
   * Protobuf type {@code cn.wzj.netty.proto.S2C_UserData}
   */
  public  static final class S2C_UserData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.wzj.netty.proto.S2C_UserData)
      S2C_UserDataOrBuilder {
    // Use S2C_UserData.newBuilder() to construct.
    private S2C_UserData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_UserData() {
      ret_ = 0;
      newUser_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_UserData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              newUser_ = input.readBool();
              break;
            }
            case 26: {
              cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = userData_.toBuilder();
              }
              userData_ = input.readMessage(cn.wzj.netty.proto.DatUserData.DAT_UserData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userData_);
                userData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_S2C_UserData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_S2C_UserData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.wzj.netty.proto.MsgUserData.S2C_UserData.class, cn.wzj.netty.proto.MsgUserData.S2C_UserData.Builder.class);
    }

    private int bitField0_;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>required int32 ret = 1;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }

    public static final int NEWUSER_FIELD_NUMBER = 2;
    private boolean newUser_;
    /**
     * <pre>
     * �Ƿ����û�
     * </pre>
     *
     * <code>required bool newUser = 2;</code>
     */
    public boolean hasNewUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * �Ƿ����û�
     * </pre>
     *
     * <code>required bool newUser = 2;</code>
     */
    public boolean getNewUser() {
      return newUser_;
    }

    public static final int USERDATA_FIELD_NUMBER = 3;
    private cn.wzj.netty.proto.DatUserData.DAT_UserData userData_;
    /**
     * <pre>
     *���ҵ���Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
     */
    public boolean hasUserData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *���ҵ���Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
     */
    public cn.wzj.netty.proto.DatUserData.DAT_UserData getUserData() {
      return userData_ == null ? cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance() : userData_;
    }
    /**
     * <pre>
     *���ҵ���Ϣ
     * </pre>
     *
     * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
     */
    public cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder getUserDataOrBuilder() {
      return userData_ == null ? cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance() : userData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUserData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, newUser_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getUserData());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, newUser_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUserData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.wzj.netty.proto.MsgUserData.S2C_UserData)) {
        return super.equals(obj);
      }
      cn.wzj.netty.proto.MsgUserData.S2C_UserData other = (cn.wzj.netty.proto.MsgUserData.S2C_UserData) obj;

      boolean result = true;
      result = result && (hasRet() == other.hasRet());
      if (hasRet()) {
        result = result && (getRet()
            == other.getRet());
      }
      result = result && (hasNewUser() == other.hasNewUser());
      if (hasNewUser()) {
        result = result && (getNewUser()
            == other.getNewUser());
      }
      result = result && (hasUserData() == other.hasUserData());
      if (hasUserData()) {
        result = result && getUserData()
            .equals(other.getUserData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRet()) {
        hash = (37 * hash) + RET_FIELD_NUMBER;
        hash = (53 * hash) + getRet();
      }
      if (hasNewUser()) {
        hash = (37 * hash) + NEWUSER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNewUser());
      }
      if (hasUserData()) {
        hash = (37 * hash) + USERDATA_FIELD_NUMBER;
        hash = (53 * hash) + getUserData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.wzj.netty.proto.MsgUserData.S2C_UserData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.wzj.netty.proto.S2C_UserData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.wzj.netty.proto.S2C_UserData)
        cn.wzj.netty.proto.MsgUserData.S2C_UserDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_S2C_UserData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_S2C_UserData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.wzj.netty.proto.MsgUserData.S2C_UserData.class, cn.wzj.netty.proto.MsgUserData.S2C_UserData.Builder.class);
      }

      // Construct using cn.wzj.netty.proto.MsgUserData.S2C_UserData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        newUser_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (userDataBuilder_ == null) {
          userData_ = null;
        } else {
          userDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.wzj.netty.proto.MsgUserData.internal_static_cn_wzj_netty_proto_S2C_UserData_descriptor;
      }

      public cn.wzj.netty.proto.MsgUserData.S2C_UserData getDefaultInstanceForType() {
        return cn.wzj.netty.proto.MsgUserData.S2C_UserData.getDefaultInstance();
      }

      public cn.wzj.netty.proto.MsgUserData.S2C_UserData build() {
        cn.wzj.netty.proto.MsgUserData.S2C_UserData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.wzj.netty.proto.MsgUserData.S2C_UserData buildPartial() {
        cn.wzj.netty.proto.MsgUserData.S2C_UserData result = new cn.wzj.netty.proto.MsgUserData.S2C_UserData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.newUser_ = newUser_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (userDataBuilder_ == null) {
          result.userData_ = userData_;
        } else {
          result.userData_ = userDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.wzj.netty.proto.MsgUserData.S2C_UserData) {
          return mergeFrom((cn.wzj.netty.proto.MsgUserData.S2C_UserData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.wzj.netty.proto.MsgUserData.S2C_UserData other) {
        if (other == cn.wzj.netty.proto.MsgUserData.S2C_UserData.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasNewUser()) {
          setNewUser(other.getNewUser());
        }
        if (other.hasUserData()) {
          mergeUserData(other.getUserData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          return false;
        }
        if (!hasNewUser()) {
          return false;
        }
        if (!hasUserData()) {
          return false;
        }
        if (!getUserData().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.wzj.netty.proto.MsgUserData.S2C_UserData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.wzj.netty.proto.MsgUserData.S2C_UserData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ret_ ;
      /**
       * <code>required int32 ret = 1;</code>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ret = 1;</code>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      private boolean newUser_ ;
      /**
       * <pre>
       * �Ƿ����û�
       * </pre>
       *
       * <code>required bool newUser = 2;</code>
       */
      public boolean hasNewUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * �Ƿ����û�
       * </pre>
       *
       * <code>required bool newUser = 2;</code>
       */
      public boolean getNewUser() {
        return newUser_;
      }
      /**
       * <pre>
       * �Ƿ����û�
       * </pre>
       *
       * <code>required bool newUser = 2;</code>
       */
      public Builder setNewUser(boolean value) {
        bitField0_ |= 0x00000002;
        newUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �Ƿ����û�
       * </pre>
       *
       * <code>required bool newUser = 2;</code>
       */
      public Builder clearNewUser() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newUser_ = false;
        onChanged();
        return this;
      }

      private cn.wzj.netty.proto.DatUserData.DAT_UserData userData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatUserData.DAT_UserData, cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder, cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder> userDataBuilder_;
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      public boolean hasUserData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      public cn.wzj.netty.proto.DatUserData.DAT_UserData getUserData() {
        if (userDataBuilder_ == null) {
          return userData_ == null ? cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance() : userData_;
        } else {
          return userDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      public Builder setUserData(cn.wzj.netty.proto.DatUserData.DAT_UserData value) {
        if (userDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userData_ = value;
          onChanged();
        } else {
          userDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      public Builder setUserData(
          cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder builderForValue) {
        if (userDataBuilder_ == null) {
          userData_ = builderForValue.build();
          onChanged();
        } else {
          userDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      public Builder mergeUserData(cn.wzj.netty.proto.DatUserData.DAT_UserData value) {
        if (userDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              userData_ != null &&
              userData_ != cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance()) {
            userData_ =
              cn.wzj.netty.proto.DatUserData.DAT_UserData.newBuilder(userData_).mergeFrom(value).buildPartial();
          } else {
            userData_ = value;
          }
          onChanged();
        } else {
          userDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      public Builder clearUserData() {
        if (userDataBuilder_ == null) {
          userData_ = null;
          onChanged();
        } else {
          userDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      public cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder getUserDataBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getUserDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      public cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder getUserDataOrBuilder() {
        if (userDataBuilder_ != null) {
          return userDataBuilder_.getMessageOrBuilder();
        } else {
          return userData_ == null ?
              cn.wzj.netty.proto.DatUserData.DAT_UserData.getDefaultInstance() : userData_;
        }
      }
      /**
       * <pre>
       *���ҵ���Ϣ
       * </pre>
       *
       * <code>required .cn.wzj.netty.proto.DAT_UserData userData = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.wzj.netty.proto.DatUserData.DAT_UserData, cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder, cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder> 
          getUserDataFieldBuilder() {
        if (userDataBuilder_ == null) {
          userDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.wzj.netty.proto.DatUserData.DAT_UserData, cn.wzj.netty.proto.DatUserData.DAT_UserData.Builder, cn.wzj.netty.proto.DatUserData.DAT_UserDataOrBuilder>(
                  getUserData(),
                  getParentForChildren(),
                  isClean());
          userData_ = null;
        }
        return userDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.wzj.netty.proto.S2C_UserData)
    }

    // @@protoc_insertion_point(class_scope:cn.wzj.netty.proto.S2C_UserData)
    private static final cn.wzj.netty.proto.MsgUserData.S2C_UserData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.wzj.netty.proto.MsgUserData.S2C_UserData();
    }

    public static cn.wzj.netty.proto.MsgUserData.S2C_UserData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_UserData>
        PARSER = new com.google.protobuf.AbstractParser<S2C_UserData>() {
      public S2C_UserData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new S2C_UserData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_UserData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_UserData> getParserForType() {
      return PARSER;
    }

    public cn.wzj.netty.proto.MsgUserData.S2C_UserData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_C2S_UserData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_C2S_UserData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_wzj_netty_proto_S2C_UserData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_wzj_netty_proto_S2C_UserData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Msg_UserData.proto\022\022cn.wzj.netty.proto" +
      "\032\022Dat_UserData.proto\")\n\014C2S_UserData\022\013\n\003" +
      "uid\030\001 \002(\t\022\014\n\004code\030\002 \002(\t\"`\n\014S2C_UserData\022" +
      "\013\n\003ret\030\001 \002(\005\022\017\n\007newUser\030\002 \002(\010\0222\n\010userDat" +
      "a\030\003 \002(\0132 .cn.wzj.netty.proto.DAT_UserDat" +
      "a"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.wzj.netty.proto.DatUserData.getDescriptor(),
        }, assigner);
    internal_static_cn_wzj_netty_proto_C2S_UserData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_wzj_netty_proto_C2S_UserData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_C2S_UserData_descriptor,
        new java.lang.String[] { "Uid", "Code", });
    internal_static_cn_wzj_netty_proto_S2C_UserData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_wzj_netty_proto_S2C_UserData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_wzj_netty_proto_S2C_UserData_descriptor,
        new java.lang.String[] { "Ret", "NewUser", "UserData", });
    cn.wzj.netty.proto.DatUserData.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
